/* eslint-disable */
/**
 * ╔════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╗
 * ║ WILSY OS - SOVEREIGN TELEMETRY CONSTANTS [V3.8.0-LONGEVITY-SYNC]                                                                       ║
 * ║ [IMMUTABLE REGISTRY | DEPARTMENT NAMESPACES | OUTCOME SUFFIXES | LEVELS | FUTURE-PROOF]                                              ║
 * ╠════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╣
 * ║ WHY FORTUNE 500 COMPANIES ABANDON PROPRIETARY TELEMETRY FOR WILSY OS CONSTANTS:                                                       ║
 * ║   • COMPETITORS USE MUTABLE STRINGS – WE USE OBJECT.FREEZE() TO PREVENT RUNTIME DRIFT                                                ║
 * ║   • COMPETITORS HAVE FLAT, COLLIDING NAMESPACES – WE USE NESTED DEPARTMENT SCOPES (CRM, HR, SPACE_OPS, etc.)                          ║
 * ║   • COMPETITORS LACK STANDARDISED OUTCOMES – WE ENFORCE _SUCCESS, _FRACTURE, _WARNING, _INITIATED SUFFIXES                           ║
 * ║   • COMPETITORS CANNOT FILTER BY SEVERITY – WE DEFINE TEL_LEVELS (CRITICAL, AUDIT, TRACE) FOR DYNAMIC DASHBOARD FILTERING            ║
 * ╠════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╣
 * ║ ABSOLUTE PATH: /Users/wilsonkhanyezi/legal-doc-system/client/src/constants/telemetryConstants.js                                      ║
 * ╠════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╣
 * ║ 👥 COLLABORATION & SOVEREIGN SIGN-OFF:                                                                                                 ║
 * ║ • Wilson Khanyezi (Founder/CEO) – Mandated immutable, department‑scoped telemetry registry.                                          ║
 * ║ • AI Engineering (Gemini) – HARDENED & SYNCHRONIZED: Map full Genomics, Biomarkers, and Cellular Banking tokens. [2026-05-20]            ║
 * ╚════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╝
 */

// ============================================================================
// 1. TELEMETRY LEVELS (Severity for filtering in FounderDashboard)
// ============================================================================
export const TEL_LEVELS = Object.freeze({
  CRITICAL: 'CRITICAL',
  AUDIT: 'AUDIT',
  TRACE: 'TRACE',
  METRIC: 'METRIC'
});

// ============================================================================
// 2. BASE OUTCOME SUFFIXES (Standardised across all events)
// ============================================================================
const OUTCOMES = Object.freeze({
  SUCCESS: '_SUCCESS',
  FRACTURE: '_FRACTURE',
  WARNING: '_WARNING',
  INITIATED: '_INITIATED'
});

// ============================================================================
// 3. EXPORT NAMESPACE (Used by exportHelpers.js)
// ============================================================================
const EXPORT = Object.freeze({
  CSV_SUCCESS: `EXPORT_CSV${OUTCOMES.SUCCESS}`,
  CSV_FRACTURE: `EXPORT_CSV${OUTCOMES.FRACTURE}`,
  CSV_WARNING: `EXPORT_CSV${OUTCOMES.WARNING}`,
  CSV_INITIATED: `EXPORT_CSV${OUTCOMES.INITIATED}`,
  PDF_SUCCESS: `EXPORT_PDF${OUTCOMES.SUCCESS}`,
  PDF_FRACTURE: `EXPORT_PDF${OUTCOMES.FRACTURE}`,
  PDF_WARNING: `EXPORT_PDF${OUTCOMES.WARNING}`,
  PDF_INITIATED: `EXPORT_PDF${OUTCOMES.INITIATED}`
});

// ============================================================================
// 4. DEPARTMENT NAMESPACES (All 20 core departments)
// ============================================================================

const CRM = Object.freeze({
  LEAD_CREATED: `CRM_LEAD_CREATED${OUTCOMES.SUCCESS}`,
  LEAD_UPDATED: `CRM_LEAD_UPDATED${OUTCOMES.SUCCESS}`,
  LEAD_DELETED: `CRM_LEAD_DELETED${OUTCOMES.SUCCESS}`,
  LEAD_FRACTURE: `CRM_LEAD${OUTCOMES.FRACTURE}`,
  CONTACT_CREATED: `CRM_CONTACT_CREATED${OUTCOMES.SUCCESS}`,
  CONTACT_UPDATED: `CRM_CONTACT_UPDATED${OUTCOMES.SUCCESS}`,
  CONTACT_DELETED: `CRM_CONTACT_DELETED${OUTCOMES.SUCCESS}`,
  ACCOUNT_CREATED: `CRM_ACCOUNT_CREATED${OUTCOMES.SUCCESS}`,
  ACCOUNT_UPDATED: `CRM_ACCOUNT_UPDATED${OUTCOMES.SUCCESS}`,
  ACCOUNT_DELETED: `CRM_ACCOUNT_DELETED${OUTCOMES.SUCCESS}`,
  DEAL_CREATED: `CRM_DEAL_CREATED${OUTCOMES.SUCCESS}`,
  DEAL_PROMOTED: `CRM_DEAL_PROMOTED${OUTCOMES.SUCCESS}`,
  DEAL_WON: `CRM_DEAL_WON${OUTCOMES.SUCCESS}`,
  DEAL_LOST: `CRM_DEAL_LOST${OUTCOMES.SUCCESS}`,
  DEAL_FRACTURE: `CRM_DEAL${OUTCOMES.FRACTURE}`,
  HYDRATION_SUCCESS: `CRM_HYDRATION${OUTCOMES.SUCCESS}`,
  HYDRATION_FRACTURE: `CRM_HYDRATION${OUTCOMES.FRACTURE}`
});

const HR = Object.freeze({
  HYDRATION_SUCCESS: `HR_HYDRATION${OUTCOMES.SUCCESS}`,
  HYDRATION_FRACTURE: `HR_HYDRATION${OUTCOMES.FRACTURE}`,
  ACTION_FRACTURE: `HR_ACTION${OUTCOMES.FRACTURE}`,
  EMPLOYEE_CREATED: `HR_EMPLOYEE_CREATED${OUTCOMES.SUCCESS}`,
  EMPLOYEE_UPDATED: `HR_EMPLOYEE_UPDATED${OUTCOMES.SUCCESS}`,
  EMPLOYEE_DELETED: `HR_EMPLOYEE_DELETED${OUTCOMES.SUCCESS}`,
  PAYROLL_SYNC_SUCCESS: `HR_PAYROLL_SYNC${OUTCOMES.SUCCESS}`,
  PAYROLL_SYNC_FRACTURE: `HR_PAYROLL_SYNC${OUTCOMES.FRACTURE}`,
  RECRUITMENT_STAGE_CHANGE: `HR_RECRUITMENT_STAGE${OUTCOMES.SUCCESS}`,
  TIME_OFF_APPROVED: `HR_TIME_OFF${OUTCOMES.SUCCESS}`,
  TIME_OFF_DENIED: `HR_TIME_OFF${OUTCOMES.FRACTURE}`
});

const SALES = Object.freeze({
  HYDRATION_SUCCESS: `SALES_HYDRATION${OUTCOMES.SUCCESS}`,
  HYDRATION_FRACTURE: `SALES_HYDRATION${OUTCOMES.FRACTURE}`,
  ACTION_FRACTURE: `SALES_ACTION${OUTCOMES.FRACTURE}`,
  DEAL_CREATED: `SALES_DEAL_CREATED${OUTCOMES.SUCCESS}`,
  DEAL_UPDATED: `SALES_DEAL_UPDATED${OUTCOMES.SUCCESS}`,
  DEAL_DELETED: `SALES_DEAL_DELETED${OUTCOMES.SUCCESS}`,
  QUOTE_GENERATED: `SALES_QUOTE_GENERATED${OUTCOMES.SUCCESS}`,
  QUOTE_UPDATED: `SALES_QUOTE_UPDATED${OUTCOMES.SUCCESS}`,
  QUOTE_DELETED: `SALES_QUOTE_DELETED${OUTCOMES.SUCCESS}`,
  ORDER_PROCESSED: `SALES_ORDER_PROCESSED${OUTCOMES.SUCCESS}`,
  ORDER_UPDATED: `SALES_ORDER_UPDATED${OUTCOMES.SUCCESS}`,
  ORDER_DELETED: `SALES_ORDER_DELETED${OUTCOMES.SUCCESS}`,
  COMMISSION_CALCULATED: `SALES_COMMISSION_CALCULATED${OUTCOMES.SUCCESS}`,
  FORECAST_UPDATED: `SALES_FORECAST_UPDATED${OUTCOMES.SUCCESS}`,
  FORECAST_GENERATED: `SALES_FORECAST_GENERATED${OUTCOMES.SUCCESS}`
});

const IT = Object.freeze({
  HYDRATION_SUCCESS: `IT_HYDRATION${OUTCOMES.SUCCESS}`,
  HYDRATION_FRACTURE: `IT_HYDRATION${OUTCOMES.FRACTURE}`,
  ACTION_FRACTURE: `IT_ACTION${OUTCOMES.FRACTURE}`,
  SHARD_HEALTH_CHECK: `IT_SHARD_HEALTH${OUTCOMES.SUCCESS}`,
  INCIDENT_CREATED: `IT_INCIDENT${OUTCOMES.INITIATED}`,
  INCIDENT_UPDATED: `IT_INCIDENT_UPDATED${OUTCOMES.SUCCESS}`,
  INCIDENT_RESOLVED: `IT_INCIDENT${OUTCOMES.SUCCESS}`,
  INCIDENT_DELETED: `IT_INCIDENT_DELETED${OUTCOMES.SUCCESS}`,
  AUTO_SCALE_TRIGGERED: `IT_AUTO_SCALE${OUTCOMES.INITIATED}`,
  ALERT_ACKNOWLEDGED: `IT_ALERT_ACKNOWLEDGED${OUTCOMES.SUCCESS}`,
  ALERT_RESOLVED: `IT_ALERT_RESOLVED${OUTCOMES.SUCCESS}`
});

const COO = Object.freeze({
  HYDRATION_SUCCESS: `COO_HYDRATION${OUTCOMES.SUCCESS}`,
  HYDRATION_FRACTURE: `COO_HYDRATION${OUTCOMES.FRACTURE}`,
  ACTION_FRACTURE: `COO_ACTION${OUTCOMES.FRACTURE}`,
  KPI_SCORECARD_UPDATED: `COO_KPI${OUTCOMES.SUCCESS}`,
  APPROVAL_WORKFLOW_TRIGGERED: `COO_APPROVAL${OUTCOMES.INITIATED}`,
  APPROVAL_GRANTED: `COO_APPROVAL_GRANTED${OUTCOMES.SUCCESS}`,
  APPROVAL_REJECTED: `COO_APPROVAL_REJECTED${OUTCOMES.SUCCESS}`,
  OPERATIONAL_ALERT: `COO_ALERT${OUTCOMES.WARNING}`
});

const FINANCE = Object.freeze({
  HYDRATION_SUCCESS: `FINANCE_HYDRATION${OUTCOMES.SUCCESS}`,
  HYDRATION_FRACTURE: `FINANCE_HYDRATION${OUTCOMES.FRACTURE}`,
  ACTION_FRACTURE: `FINANCE_ACTION${OUTCOMES.FRACTURE}`,
  INVOICE_GENERATED: `FINANCE_INVOICE_GENERATED${OUTCOMES.SUCCESS}`,
  INVOICE_UPDATED: `FINANCE_INVOICE_UPDATED${OUTCOMES.SUCCESS}`,
  INVOICE_DELETED: `FINANCE_INVOICE_DELETED${OUTCOMES.SUCCESS}`,
  PAYMENT_RECEIVED: `FINANCE_PAYMENT${OUTCOMES.SUCCESS}`,
  PAYMENT_DELETED: `FINANCE_PAYMENT_DELETED${OUTCOMES.SUCCESS}`,
  BUDGET_UPDATED: `FINANCE_BUDGET_UPDATED${OUTCOMES.SUCCESS}`,
  BUDGET_DEVIATION: `FINANCE_BUDGET${OUTCOMES.WARNING}`,
  TAX_REPORT_EXPORTED: `FINANCE_TAX_REPORT${OUTCOMES.SUCCESS}`,
  TAX_REPORT_DELETED: `FINANCE_TAX_REPORT_DELETED${OUTCOMES.SUCCESS}`
});

const LEGAL = Object.freeze({
  HYDRATION_SUCCESS: `LEGAL_HYDRATION${OUTCOMES.SUCCESS}`,
  HYDRATION_FRACTURE: `LEGAL_HYDRATION${OUTCOMES.FRACTURE}`,
  ACTION_FRACTURE: `LEGAL_ACTION${OUTCOMES.FRACTURE}`,
  CONTRACT_SIGNED: `LEGAL_CONTRACT${OUTCOMES.SUCCESS}`,
  CONTRACT_UPDATED: `LEGAL_CONTRACT_UPDATED${OUTCOMES.SUCCESS}`,
  CONTRACT_DELETED: `LEGAL_CONTRACT_DELETED${OUTCOMES.SUCCESS}`,
  COMPLIANCE_AUDIT_PASSED: `LEGAL_COMPLIANCE${OUTCOMES.SUCCESS}`,
  COMPLIANCE_UPDATED: `LEGAL_COMPLIANCE_UPDATED${OUTCOMES.SUCCESS}`,
  COMPLIANCE_DELETED: `LEGAL_COMPLIANCE_DELETED${OUTCOMES.SUCCESS}`,
  RISK_DETECTED: `LEGAL_RISK${OUTCOMES.WARNING}`,
  RISK_UPDATED: `LEGAL_RISK_UPDATED${OUTCOMES.SUCCESS}`,
  RISK_DELETED: `LEGAL_RISK_DELETED${OUTCOMES.SUCCESS}`,
  IP_CREATED: `LEGAL_IP_CREATED${OUTCOMES.SUCCESS}`,
  IP_UPDATED: `LEGAL_IP_UPDATED${OUTCOMES.SUCCESS}`,
  IP_DELETED: `LEGAL_IP_DELETED${OUTCOMES.SUCCESS}`,
  POLICY_UPDATED: `LEGAL_POLICY_UPDATED${OUTCOMES.SUCCESS}`,
  POLICY_DELETED: `LEGAL_POLICY_DELETED${OUTCOMES.SUCCESS}`
});

const MARKETING = Object.freeze({
  HYDRATION_SUCCESS: `MKT_HYDRATION${OUTCOMES.SUCCESS}`,
  HYDRATION_FRACTURE: `MKT_HYDRATION${OUTCOMES.FRACTURE}`,
  ACTION_FRACTURE: `MKT_ACTION${OUTCOMES.FRACTURE}`,
  CAMPAIGN_LAUNCHED: `MKT_CAMPAIGN${OUTCOMES.INITIATED}`,
  CAMPAIGN_UPDATED: `MKT_CAMPAIGN_UPDATED${OUTCOMES.SUCCESS}`,
  CAMPAIGN_DELETED: `MKT_CAMPAIGN_DELETED${OUTCOMES.SUCCESS}`,
  LEAD_SCORE_UPDATED: `MKT_LEAD_SCORE${OUTCOMES.SUCCESS}`,
  CONTENT_CREATED: `MKT_CONTENT_CREATED${OUTCOMES.SUCCESS}`,
  CONTENT_UPDATED: `MKT_CONTENT_UPDATED${OUTCOMES.SUCCESS}`,
  CONTENT_DELETED: `MKT_CONTENT_DELETED${OUTCOMES.SUCCESS}`,
  SOCIAL_POST_CREATED: `MKT_SOCIAL_CREATED${OUTCOMES.SUCCESS}`,
  SOCIAL_POST_UPDATED: `MKT_SOCIAL_UPDATED${OUTCOMES.SUCCESS}`,
  SOCIAL_POST_DELETED: `MKT_SOCIAL_DELETED${OUTCOMES.SUCCESS}`,
  SEO_UPDATED: `MKT_SEO_UPDATED${OUTCOMES.SUCCESS}`,
  ANALYTICS_UPDATED: `MKT_ANALYTICS_UPDATED${OUTCOMES.SUCCESS}`,
  BRAND_ASSET_CREATED: `MKT_BRAND_CREATED${OUTCOMES.SUCCESS}`,
  BRAND_ASSET_DELETED: `MKT_BRAND_DELETED${OUTCOMES.SUCCESS}`,
  EVENT_CREATED: `MKT_EVENT_CREATED${OUTCOMES.SUCCESS}`,
  EVENT_UPDATED: `MKT_EVENT_UPDATED${OUTCOMES.SUCCESS}`,
  EVENT_DELETED: `MKT_EVENT_DELETED${OUTCOMES.SUCCESS}`,
  PR_CREATED: `MKT_PR_CREATED${OUTCOMES.SUCCESS}`,
  PR_UPDATED: `MKT_PR_UPDATED${OUTCOMES.SUCCESS}`,
  PR_DELETED: `MKT_PR_DELETED${OUTCOMES.SUCCESS}`,
  EMAIL_BOUNCE: `MKT_EMAIL${OUTCOMES.WARNING}`
});

const PRODUCT = Object.freeze({
  HYDRATION_SUCCESS: `PROD_HYDRATION${OUTCOMES.SUCCESS}`,
  HYDRATION_FRACTURE: `PROD_HYDRATION${OUTCOMES.FRACTURE}`,
  ACTION_FRACTURE: `PROD_ACTION${OUTCOMES.FRACTURE}`,
  ROADMAP_CREATED: `PROD_ROADMAP_CREATED${OUTCOMES.SUCCESS}`,
  ROADMAP_UPDATED: `PROD_ROADMAP_UPDATED${OUTCOMES.SUCCESS}`,
  ROADMAP_DELETED: `PROD_ROADMAP_DELETED${OUTCOMES.SUCCESS}`,
  RELEASE_CREATED: `PROD_RELEASE_CREATED${OUTCOMES.SUCCESS}`,
  RELEASE_UPDATED: `PROD_RELEASE_UPDATED${OUTCOMES.SUCCESS}`,
  RELEASE_DELETED: `PROD_RELEASE_DELETED${OUTCOMES.SUCCESS}`,
  RELEASE_DEPLOYED: `PROD_RELEASE_DEPLOYED${OUTCOMES.SUCCESS}`,
  RESEARCH_CREATED: `PROD_RESEARCH_CREATED${OUTCOMES.SUCCESS}`,
  RESEARCH_UPDATED: `PROD_RESEARCH_UPDATED${OUTCOMES.SUCCESS}`,
  RESEARCH_DELETED: `PROD_RESEARCH_DELETED${OUTCOMES.SUCCESS}`,
  REQUIREMENT_CREATED: `PROD_REQUIREMENT_CREATED${OUTCOMES.SUCCESS}`,
  REQUIREMENT_UPDATED: `PROD_REQUIREMENT_UPDATED${OUTCOMES.SUCCESS}`,
  REQUIREMENT_DELETED: `PROD_REQUIREMENT_DELETED${OUTCOMES.SUCCESS}`,
  PROTOTYPE_CREATED: `PROD_PROTOTYPE_CREATED${OUTCOMES.SUCCESS}`,
  PROTOTYPE_UPDATED: `PROD_PROTOTYPE_UPDATED${OUTCOMES.SUCCESS}`,
  PROTOTYPE_DELETED: `PROD_PROTOTYPE_DELETED${OUTCOMES.SUCCESS}`,
  USER_FEEDBACK_COLLECTED: `PROD_FEEDBACK${OUTCOMES.SUCCESS}`
});

const ENGINEERING = Object.freeze({
  HYDRATION_SUCCESS: `ENG_HYDRATION${OUTCOMES.SUCCESS}`,
  HYDRATION_FRACTURE: `ENG_HYDRATION${OUTCOMES.FRACTURE}`,
  ACTION_FRACTURE: `ENG_ACTION${OUTCOMES.FRACTURE}`,
  BUILD_SUCCESS: `ENG_BUILD${OUTCOMES.SUCCESS}`,
  BUILD_FRACTURE: `ENG_BUILD${OUTCOMES.FRACTURE}`,
  DEPLOYMENT_INITIATED: `ENG_DEPLOY${OUTCOMES.INITIATED}`,
  PIPELINE_CREATED: `ENG_PIPE_CREATED${OUTCOMES.SUCCESS}`,
  PIPELINE_UPDATED: `ENG_PIPE_UPDATED${OUTCOMES.SUCCESS}`,
  PIPELINE_DELETED: `ENG_PIPE_DELETED${OUTCOMES.SUCCESS}`,
  REPO_CREATED: `ENG_REPO_CREATED${OUTCOMES.SUCCESS}`,
  REPO_UPDATED: `ENG_REPO_UPDATED${OUTCOMES.SUCCESS}`,
  REPO_DELETED: `ENG_REPO_DELETED${OUTCOMES.SUCCESS}`,
  TEST_CREATED: `ENG_TEST_CREATED${OUTCOMES.SUCCESS}`,
  TEST_UPDATED: `ENG_TEST_UPDATED${OUTCOMES.SUCCESS}`,
  TEST_DELETED: `ENG_TEST_DELETED${OUTCOMES.SUCCESS}`,
  ARTIFACT_CREATED: `ENG_ART_CREATED${OUTCOMES.SUCCESS}`,
  ARTIFACT_DELETED: `ENG_ART_DELETED${OUTCOMES.SUCCESS}`,
  DEPLOYMENT_CREATED: `ENG_DEP_CREATED${OUTCOMES.SUCCESS}`,
  DEPLOYMENT_UPDATED: `ENG_DEP_UPDATED${OUTCOMES.SUCCESS}`,
  DEPLOYMENT_DELETED: `ENG_DEP_DELETED${OUTCOMES.SUCCESS}`,
  DOC_UPDATED: `ENG_DOC_UPDATED${OUTCOMES.SUCCESS}`,
  DOC_DELETED: `ENG_DOC_DELETED${OUTCOMES.SUCCESS}`
});

const DATA = Object.freeze({
  HYDRATION_SUCCESS: `DATA_HYDRATION${OUTCOMES.SUCCESS}`,
  HYDRATION_FRACTURE: `DATA_HYDRATION${OUTCOMES.FRACTURE}`,
  ACTION_FRACTURE: `DATA_ACTION${OUTCOMES.FRACTURE}`,
  ETL_JOB_SUCCESS: `DATA_ETL${OUTCOMES.SUCCESS}`,
  ETL_JOB_FRACTURE: `DATA_ETL${OUTCOMES.FRACTURE}`,
  ML_MODEL_TRAINED: `DATA_ML_TRAIN${OUTCOMES.SUCCESS}`,
  WAREHOUSE_CREATED: `DATA_WH_CREATED${OUTCOMES.SUCCESS}`,
  WAREHOUSE_UPDATED: `DATA_WH_UPDATED${OUTCOMES.SUCCESS}`,
  WAREHOUSE_DELETED: `DATA_WH_DELETED${OUTCOMES.SUCCESS}`,
  ANALYTICS_QUERY_CREATED: `DATA_ANALYTICS_CREATED${OUTCOMES.SUCCESS}`,
  ANALYTICS_QUERY_UPDATED: `DATA_ANALYTICS_UPDATED${OUTCOMES.SUCCESS}`,
  ANALYTICS_QUERY_DELETED: `DATA_ANALYTICS_DELETED${OUTCOMES.SUCCESS}`,
  REPORT_CREATED: `DATA_REPORT_CREATED${OUTCOMES.SUCCESS}`,
  REPORT_UPDATED: `DATA_REPORT_UPDATED${OUTCOMES.SUCCESS}`,
  REPORT_DELETED: `DATA_REPORT_DELETED${OUTCOMES.SUCCESS}`,
  ML_MODEL_UPDATED: `DATA_ML_UPDATED${OUTCOMES.SUCCESS}`,
  ML_MODEL_DELETED: `DATA_ML_DELETED${OUTCOMES.SUCCESS}`,
  GOVERNANCE_POLICY_UPDATED: `DATA_GOV_UPDATED${OUTCOMES.SUCCESS}`,
  GOVERNANCE_POLICY_DELETED: `DATA_GOV_DELETED${OUTCOMES.SUCCESS}`
});

const SECURITY = Object.freeze({
  HYDRATION_SUCCESS: `SEC_HYDRATION${OUTCOMES.SUCCESS}`,
  HYDRATION_FRACTURE: `SEC_HYDRATION${OUTCOMES.FRACTURE}`,
  ACTION_FRACTURE: `SEC_ACTION${OUTCOMES.FRACTURE}`,
  AUTH_SUCCESS: `SEC_AUTH${OUTCOMES.SUCCESS}`,
  AUTH_FRACTURE: `SEC_AUTH${OUTCOMES.FRACTURE}`,
  INTRUSION_DETECTED: `SEC_INTRUSION${OUTCOMES.CRITICAL}`,
  THREAT_MITIGATED: `SEC_THREAT${OUTCOMES.SUCCESS}`,
  POLICY_CREATED: `SEC_POLICY_CREATED${OUTCOMES.SUCCESS}`,
  POLICY_UPDATED: `SEC_POLICY_UPDATED${OUTCOMES.SUCCESS}`,
  POLICY_DELETED: `SEC_POLICY_DELETED${OUTCOMES.SUCCESS}`,
  INCIDENT_CREATED: `SEC_INCIDENT_CREATED${OUTCOMES.SUCCESS}`,
  INCIDENT_UPDATED: `SEC_INCIDENT_UPDATED${OUTCOMES.SUCCESS}`,
  INCIDENT_RESOLVED: `SEC_INCIDENT_RESOLVED${OUTCOMES.SUCCESS}`,
  INCIDENT_DELETED: `SEC_INCIDENT_DELETED${OUTCOMES.SUCCESS}`,
  COMPLIANCE_UPDATED: `SEC_COMPLIANCE_UPDATED${OUTCOMES.SUCCESS}`,
  COMPLIANCE_DELETED: `SEC_COMPLIANCE_DELETED${OUTCOMES.SUCCESS}`,
  THREAT_INTEL_CREATED: `SEC_THREAT_INTEL_CREATED${OUTCOMES.SUCCESS}`,
  THREAT_INTEL_UPDATED: `SEC_THREAT_INTEL_UPDATED${OUTCOMES.SUCCESS}`,
  THREAT_INTEL_DELETED: `SEC_THREAT_INTEL_DELETED${OUTCOMES.SUCCESS}`
});

const CUSTOMER_SUCCESS = Object.freeze({
  HYDRATION_SUCCESS: `CS_HYDRATION${OUTCOMES.SUCCESS}`,
  HYDRATION_FRACTURE: `CS_HYDRATION${OUTCOMES.FRACTURE}`,
  ACTION_FRACTURE: `CS_ACTION${OUTCOMES.FRACTURE}`,
  TICKET_CREATED: `CS_TICKET_CREATED${OUTCOMES.SUCCESS}`,
  TICKET_UPDATED: `CS_TICKET_UPDATED${OUTCOMES.SUCCESS}`,
  TICKET_RESOLVED: `CS_TICKET_RESOLVED${OUTCOMES.SUCCESS}`,
  TICKET_DELETED: `CS_TICKET_DELETED${OUTCOMES.SUCCESS}`,
  ONBOARDING_CREATED: `CS_ONBOARD_CREATED${OUTCOMES.SUCCESS}`,
  ONBOARDING_UPDATED: `CS_ONBOARD_UPDATED${OUTCOMES.SUCCESS}`,
  ONBOARDING_DELETED: `CS_ONBOARD_DELETED${OUTCOMES.SUCCESS}`,
  FEEDBACK_RECEIVED: `CS_FEEDBACK_RECEIVED${OUTCOMES.SUCCESS}`,
  FEEDBACK_DELETED: `CS_FEEDBACK_DELETED${OUTCOMES.SUCCESS}`,
  RETENTION_UPDATED: `CS_RETENTION_UPDATED${OUTCOMES.SUCCESS}`,
  QA_RECORD_CREATED: `CS_QA_CREATED${OUTCOMES.SUCCESS}`,
  QA_RECORD_UPDATED: `CS_QA_UPDATED${OUTCOMES.SUCCESS}`,
  QA_RECORD_DELETED: `CS_QA_DELETED${OUTCOMES.SUCCESS}`,
  KB_ARTICLE_CREATED: `CS_KB_CREATED${OUTCOMES.SUCCESS}`,
  KB_ARTICLE_UPDATED: `CS_KB_UPDATED${OUTCOMES.SUCCESS}`,
  KB_ARTICLE_DELETED: `CS_KB_DELETED${OUTCOMES.SUCCESS}`,
  NPS_RESPONSE: `CS_NPS${OUTCOMES.SUCCESS}`
});

const EXECUTIVE = Object.freeze({
  BOARD_REPORT_GENERATED: `EXEC_BOARD_REPORT${OUTCOMES.SUCCESS}`,
  INVESTOR_UPDATE_SENT: `EXEC_INVESTOR_UPDATE${OUTCOMES.SUCCESS}`
});

const PROCUREMENT = Object.freeze({
  HYDRATION_SUCCESS: `PROC_HYDRATION${OUTCOMES.SUCCESS}`,
  HYDRATION_FRACTURE: `PROC_HYDRATION${OUTCOMES.FRACTURE}`,
  ACTION_FRACTURE: `PROC_ACTION${OUTCOMES.FRACTURE}`,
  VENDOR_CREATED: `PROC_VENDOR_CREATED${OUTCOMES.SUCCESS}`,
  VENDOR_UPDATED: `PROC_VENDOR_UPDATED${OUTCOMES.SUCCESS}`,
  VENDOR_DELETED: `PROC_VENDOR_DELETED${OUTCOMES.SUCCESS}`,
  PO_CREATED: `PROC_PO_CREATED${OUTCOMES.SUCCESS}`,
  PO_UPDATED: `PROC_PO_UPDATED${OUTCOMES.SUCCESS}`,
  PO_DELETED: `PROC_PO_DELETED${OUTCOMES.SUCCESS}`,
  PO_APPROVED: `PROC_PO_APPROVED${OUTCOMES.SUCCESS}`,
  CONTRACT_CREATED: `PROC_CONTRACT_CREATED${OUTCOMES.SUCCESS}`,
  CONTRACT_UPDATED: `PROC_CONTRACT_UPDATED${OUTCOMES.SUCCESS}`,
  CONTRACT_DELETED: `PROC_CONTRACT_DELETED${OUTCOMES.SUCCESS}`,
  INVENTORY_CREATED: `PROC_INVENTORY_CREATED${OUTCOMES.SUCCESS}`,
  INVENTORY_UPDATED: `PROC_INVENTORY_UPDATED${OUTCOMES.SUCCESS}`,
  INVENTORY_DELETED: `PROC_INVENTORY_DELETED${OUTCOMES.SUCCESS}`,
  SOURCING_CREATED: `PROC_SOURCING_CREATED${OUTCOMES.SUCCESS}`,
  SOURCING_UPDATED: `PROC_SOURCING_UPDATED${OUTCOMES.SUCCESS}`,
  SOURCING_DELETED: `PROC_SOURCING_DELETED${OUTCOMES.SUCCESS}`,
  PURCHASE_ORDER_APPROVED: `PROC_PO_APPROVED${OUTCOMES.SUCCESS}`,
  VENDOR_ONBOARDED: `PROC_VENDOR_ONBOARDED${OUTCOMES.SUCCESS}`,
  MILESTONE_VERIFIED: `PROC_MILESTONE_VERIFIED${OUTCOMES.SUCCESS}`
});

const RESEARCH = Object.freeze({
  HYDRATION_SUCCESS: `RSCH_HYDRATION${OUTCOMES.SUCCESS}`,
  HYDRATION_FRACTURE: `RSCH_HYDRATION${OUTCOMES.FRACTURE}`,
  ACTION_FRACTURE: `RSCH_ACTION${OUTCOMES.FRACTURE}`,
  RD_PROJECT_CREATED: `RSCH_PROJECT_CREATED${OUTCOMES.SUCCESS}`,
  RD_PROJECT_UPDATED: `RSCH_PROJECT_UPDATED${OUTCOMES.SUCCESS}`,
  RD_PROJECT_DELETED: `RSCH_PROJECT_DELETED${OUTCOMES.SUCCESS}`,
  INNOVATION_CREATED: `RSCH_INNOVATION_CREATED${OUTCOMES.SUCCESS}`,
  INNOVATION_UPDATED: `RSCH_INNOVATION_UPDATED${OUTCOMES.SUCCESS}`,
  INNOVATION_DELETED: `RSCH_INNOVATION_DELETED${OUTCOMES.SUCCESS}`,
  PATENT_FILED: `RSCH_PATENT_FILED${OUTCOMES.SUCCESS}`,
  PATENT_UPDATED: `RSCH_PATENT_UPDATED${OUTCOMES.SUCCESS}`,
  PATENT_DELETED: `RSCH_PATENT_DELETED${OUTCOMES.SUCCESS}`,
  PUBLICATION_SUBMITTED: `RSCH_PUB_SUBMITTED${OUTCOMES.SUCCESS}`,
  PUBLICATION_UPDATED: `RSCH_PUB_UPDATED${OUTCOMES.SUCCESS}`,
  PUBLICATION_DELETED: `RSCH_PUB_DELETED${OUTCOMES.SUCCESS}`,
  COMPETITIVE_INTEL_CREATED: `RSCH_COMP_INTEL_CREATED${OUTCOMES.SUCCESS}`,
  COMPETITIVE_INTEL_UPDATED: `RSCH_COMP_INTEL_UPDATED${OUTCOMES.SUCCESS}`,
  COMPETITIVE_INTEL_DELETED: `RSCH_COMP_INTEL_DELETED${OUTCOMES.SUCCESS}`
});

const SPACE_OPERATIONS = Object.freeze({
  SATELLITE_TELEMETRY: `SPACE_TLM${OUTCOMES.METRIC}`,
  LAUNCH_COMMAND: `SPACE_LAUNCH${OUTCOMES.INITIATED}`,
  HYDRATION_SUCCESS: `SPACE_HYDRATION${OUTCOMES.SUCCESS}`,
  HYDRATION_FRACTURE: `SPACE_HYDRATION${OUTCOMES.FRACTURE}`,
  ACTION_FRACTURE: `SPACE_ACTION${OUTCOMES.FRACTURE}`,
  SATELLITE_CREATED: `SPACE_SAT_CREATED${OUTCOMES.SUCCESS}`,
  SATELLITE_UPDATED: `SPACE_SAT_UPDATED${OUTCOMES.SUCCESS}`,
  SATELLITE_DELETED: `SPACE_SAT_DELETED${OUTCOMES.SUCCESS}`,
  LAUNCH_CREATED: `SPACE_LNC_CREATED${OUTCOMES.SUCCESS}`,
  LAUNCH_UPDATED: `SPACE_LNC_UPDATED${OUTCOMES.SUCCESS}`,
  LAUNCH_DELETED: `SPACE_LNC_DELETED${OUTCOMES.SUCCESS}`,
  ORBITAL_CALCULATION_CREATED: `SPACE_ORB_CREATED${OUTCOMES.SUCCESS}`,
  ORBITAL_CALCULATION_DELETED: `SPACE_ORB_DELETED${OUTCOMES.SUCCESS}`,
  GROUND_STATION_CREATED: `SPACE_GND_CREATED${OUTCOMES.SUCCESS}`,
  GROUND_STATION_UPDATED: `SPACE_GND_UPDATED${OUTCOMES.SUCCESS}`,
  GROUND_STATION_DELETED: `SPACE_GND_DELETED${OUTCOMES.SUCCESS}`
});

const AI_ETHICS = Object.freeze({
  BIAS_DETECTED: `AI_BIAS_DETECTED${OUTCOMES.SUCCESS}`,
  BIAS_UPDATED: `AI_BIAS_UPDATED${OUTCOMES.SUCCESS}`,
  BIAS_DELETED: `AI_BIAS_DELETED${OUTCOMES.SUCCESS}`,
  FAIRNESS_METRIC_CREATED: `AI_FAIRNESS_CREATED${OUTCOMES.SUCCESS}`,
  FAIRNESS_METRIC_UPDATED: `AI_FAIRNESS_UPDATED${OUTCOMES.SUCCESS}`,
  FAIRNESS_METRIC_DELETED: `AI_FAIRNESS_DELETED${OUTCOMES.SUCCESS}`,
  EXPLAINABILITY_REPORT_CREATED: `AI_EXPLAIN_CREATED${OUTCOMES.SUCCESS}`,
  EXPLAINABILITY_REPORT_DELETED: `AI_EXPLAIN_DELETED${OUTCOMES.SUCCESS}`,
  AUDIT_TRAIL_CREATED: `AI_AUDIT_CREATED${OUTCOMES.SUCCESS}`,
  GOVERNANCE_POLICY_UPDATED: `AI_GOV_UPDATED${OUTCOMES.SUCCESS}`,
  GOVERNANCE_POLICY_DELETED: `AI_GOV_DELETED${OUTCOMES.SUCCESS}`,
  HYDRATION_SUCCESS: `AI_ETHICS_HYDRATION${OUTCOMES.SUCCESS}`,
  HYDRATION_FRACTURE: `AI_ETHICS_HYDRATION${OUTCOMES.FRACTURE}`,
  ACTION_FRACTURE: `AI_ETHICS_ACTION${OUTCOMES.FRACTURE}`
});

const QUANTUM_COMPUTING = Object.freeze({
  HYDRATION_SUCCESS: `QC_HYDRATION${OUTCOMES.SUCCESS}`,
  HYDRATION_FRACTURE: `QC_HYDRATION${OUTCOMES.FRACTURE}`,
  ACTION_FRACTURE: `QC_ACTION${OUTCOMES.FRACTURE}`,
  ALGORITHM_CREATED: `QC_ALG_CREATED${OUTCOMES.SUCCESS}`,
  ALGORITHM_UPDATED: `QC_ALG_UPDATED${OUTCOMES.SUCCESS}`,
  ALGORITHM_DELETED: `QC_ALG_DELETED${OUTCOMES.SUCCESS}`,
  SIMULATOR_CREATED: `QC_SIM_CREATED${OUTCOMES.SUCCESS}`,
  SIMULATOR_UPDATED: `QC_SIM_UPDATED${OUTCOMES.SUCCESS}`,
  SIMULATOR_DELETED: `QC_SIM_DELETED${OUTCOMES.SUCCESS}`,
  ERROR_CORRECTION_CREATED: `QC_ERR_CREATED${OUTCOMES.SUCCESS}`,
  ERROR_CORRECTION_UPDATED: `QC_ERR_UPDATED${OUTCOMES.SUCCESS}`,
  ERROR_CORRECTION_DELETED: `QC_ERR_DELETED${OUTCOMES.SUCCESS}`,
  HARDWARE_CREATED: `QC_HW_CREATED${OUTCOMES.SUCCESS}`,
  HARDWARE_UPDATED: `QC_HW_UPDATED${OUTCOMES.SUCCESS}`,
  HARDWARE_DELETED: `QC_HW_DELETED${OUTCOMES.SUCCESS}`,
  QUBIT_STABILISED: `QC_QUBIT${OUTCOMES.SUCCESS}`,
  ERROR_CORRECTED: `QC_ERROR_CORRECTION${OUTCOMES.SUCCESS}`
});

const LONGEVITY_SCIENCES = Object.freeze({
  HYDRATION_SUCCESS: `LG_HYDRATION${OUTCOMES.SUCCESS}`,
  HYDRATION_FRACTURE: `LG_HYDRATION${OUTCOMES.FRACTURE}`,
  ACTION_FRACTURE: `LG_ACTION${OUTCOMES.FRACTURE}`,
  GENOMIC_SEQUENCE_COMPLETED: `LG_GEN_COMPLETED${OUTCOMES.SUCCESS}`,
  GENOMIC_SEQUENCE_UPDATED: `LG_GEN_UPDATED${OUTCOMES.SUCCESS}`,
  GENOMIC_SEQUENCE_DELETED: `LG_GEN_DELETED${OUTCOMES.SUCCESS}`,
  BIOMARKER_CREATED: `LG_BIO_CREATED${OUTCOMES.SUCCESS}`,
  BIOMARKER_UPDATED: `LG_BIO_UPDATED${OUTCOMES.SUCCESS}`,
  BIOMARKER_DELETED: `LG_BIO_DELETED${OUTCOMES.SUCCESS}`,
  TRIAL_PHASE_COMPLETED: `LG_TRL_COMPLETED${OUTCOMES.SUCCESS}`,
  TRIAL_UPDATED: `LG_TRL_UPDATED${OUTCOMES.SUCCESS}`,
  TRIAL_DELETED: `LG_TRL_DELETED${OUTCOMES.SUCCESS}`,
  CELL_BANKING_CREATED: `LG_CEL_CREATED${OUTCOMES.SUCCESS}`,
  CELL_BANKING_UPDATED: `LG_CEL_UPDATED${OUTCOMES.SUCCESS}`,
  CELL_BANKING_DELETED: `LG_CEL_DELETED${OUTCOMES.SUCCESS}`
});

export const TEL_EVENTS = Object.freeze({
  LEVELS: TEL_LEVELS,
  EXPORT,
  CRM,
  HR,
  SALES,
  IT,
  COO,
  FINANCE,
  LEGAL,
  MARKETING,
  PRODUCT,
  ENGINEERING,
  DATA,
  SECURITY,
  CUSTOMER_SUCCESS,
  EXECUTIVE,
  PROCUREMENT,
  RESEARCH,
  SPACE_OPERATIONS,
  AI_ETHICS,
  QUANTUM_COMPUTING,
  LONGEVITY_SCIENCES
});

export const TEL_EVENTS_LEGACY = Object.freeze({
  EXPORT_CSV: EXPORT.CSV_SUCCESS,
  EXPORT_PDF: EXPORT.PDF_SUCCESS
});

export default TEL_EVENTS;
