/* eslint-disable */
import PDFDocument from 'pdfkit';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const BRAND = Object.freeze({
  black: '#020403',
  ivory: '#F4EFE4',
  gold: '#D4AF37',
  muted: '#66665F',
  line: '#D8CCAA',
  panel: '#FBF8EF',
  band: '#EFE8D8',
});

const PAGE = Object.freeze({
  width: 595.28,
  height: 841.89,
  left: 52,
  top: 182,
  bottom: 744,
  contentWidth: 491,
});

let LOGO_CACHE;

/**
 * @function textValue
 * @description Converts unknown source values into safe PDF text.
 * @param {unknown} value - Unknown source value.
 * @returns {string} Clean text.
 * @collaboration Stabilizes artifact rendering when tenant source data is incomplete.
 */
function textValue(value) {
  return String(value ?? '')
    .replace(/\s+/g, ' ')
    .trim();
}

/**
 * @function compactProof
 * @description Shortens long proof values for stable footer layout.
 * @param {string} value - Proof value.
 * @returns {string} Compact proof value.
 * @collaboration Preserves forensic visibility without proof-text collisions.
 */
function compactProof(value = '') {
  const clean = textValue(value);

  if (!clean) return 'PENDING';
  if (clean.length <= 26) return clean;

  return `${clean.slice(0, 12)}...${clean.slice(-12)}`;
}

/**
 * @function titleFromType
 * @description Converts artifact type slugs into readable enterprise titles.
 * @param {string} type - Artifact type slug.
 * @returns {string} Readable title.
 * @collaboration Gives every artifact a tenant-facing title before source enrichment is complete.
 */
function titleFromType(type = 'artifact') {
  return textValue(type)
    .replace(/_/g, '-')
    .split('-')
    .filter(Boolean)
    .map((part) =>
      part.length <= 3 ? part.toUpperCase() : `${part.charAt(0).toUpperCase()}${part.slice(1)}`
    )
    .join(' ');
}

/**
 * @function safeFileName
 * @description Creates safe artifact filenames.
 * @param {string} value - Raw filename value.
 * @returns {string} Safe filename.
 * @collaboration Prevents broken tenant downloads caused by unsafe document titles.
 */
function safeFileName(value = 'artifact') {
  return (
    textValue(value)
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '') || 'artifact'
  );
}

/**
 * @function findLogoPath
 * @description Resolves the Wilsy OS logo from known client asset locations.
 * @returns {string} Existing logo path or empty string.
 * @collaboration Restores Wilsy OS branding inside backend-generated tenant PDFs.
 */
function findLogoPath() {
  if (LOGO_CACHE !== undefined) return LOGO_CACHE;

  const rendererDir = path.dirname(fileURLToPath(import.meta.url));
  const candidates = [
    path.resolve(process.cwd(), '../client/src/assets/logo/wilsy.jpeg'),
    path.resolve(process.cwd(), '../client/src/assets/logo/wilsy.jpg'),
    path.resolve(process.cwd(), '../client/src/assets/logo/wilsy.png'),
    path.resolve(process.cwd(), '../client/public/wilsy.jpeg'),
    path.resolve(process.cwd(), '../client/public/wilsy.jpg'),
    path.resolve(process.cwd(), '../client/public/wilsy.png'),
    path.resolve(rendererDir, '../../../client/src/assets/logo/wilsy.jpeg'),
    path.resolve(rendererDir, '../../../client/src/assets/logo/wilsy.jpg'),
    path.resolve(rendererDir, '../../../client/src/assets/logo/wilsy.png'),
  ];

  LOGO_CACHE = candidates.find((candidate) => fs.existsSync(candidate)) || '';
  return LOGO_CACHE;
}

/**
 * @function titleCaseHumanName
 * @description Converts a low-trust identity token into a readable human name candidate.
 * @param {string} value - Raw identity text.
 * @returns {string} Title-cased human name candidate.
 * @collaboration PDF controls, operator identity evidence, CRM Proof Pack export, and sovereign accountability.
 */
function titleCaseHumanName(value = '') {
  return textValue(value)
    .replace(/[_.-]+/g, ' ')
    .split(' ')
    .filter(Boolean)
    .map((part) => `${part.charAt(0).toUpperCase()}${part.slice(1).toLowerCase()}`)
    .join(' ');
}

/**
 * @function resolveHumanGeneratedByName
 * @description Resolves the accountable human name/surname for Generated By controls without showing system slugs.
 * @param {object} args - Identity sources.
 * @returns {string} Human display name for control surfaces.
 * @collaboration Enterprise PDF renderer, CRM export proof pack, tenant identity, and audit control ownership.
 */
function resolveHumanGeneratedByName({ proofPack = {}, identity = {}, state = {} } = {}) {
  const nestedUser =
    identity.user || identity.operator || identity.profile || identity.account || {};
  const proofUser = proofPack.user || proofPack.operator || proofPack.profile || {};

  const firstName = textValue(
    proofPack.firstName ||
      proofPack.givenName ||
      proofUser.firstName ||
      proofUser.givenName ||
      identity.firstName ||
      identity.givenName ||
      nestedUser.firstName ||
      nestedUser.givenName
  );

  const surname = textValue(
    proofPack.surname ||
      proofPack.lastName ||
      proofPack.familyName ||
      proofUser.surname ||
      proofUser.lastName ||
      proofUser.familyName ||
      identity.surname ||
      identity.lastName ||
      identity.familyName ||
      nestedUser.surname ||
      nestedUser.lastName ||
      nestedUser.familyName
  );

  const combinedName = textValue(`${firstName} ${surname}`);

  if (combinedName && combinedName.split(' ').length >= 2) {
    return combinedName;
  }

  const directName = textValue(
    proofPack.generatedByName ||
      proofPack.generatorName ||
      proofPack.operatorName ||
      proofPack.operatorDisplayName ||
      proofPack.displayName ||
      proofUser.name ||
      proofUser.displayName ||
      identity.generatedByName ||
      identity.generatorName ||
      identity.operatorName ||
      identity.operatorDisplayName ||
      identity.displayName ||
      identity.name ||
      nestedUser.name ||
      nestedUser.displayName ||
      state.generatedByName
  );

  const forbiddenSlugs = new Set(['wilsy-operator', 'operator', 'system', 'wilsy', 'anonymous']);
  const normalizedDirectName = directName.toLowerCase();

  if (directName && !forbiddenSlugs.has(normalizedDirectName)) {
    return directName;
  }

  const email = textValue(
    proofPack.operatorEmail ||
      proofPack.email ||
      proofUser.email ||
      identity.userEmail ||
      identity.email ||
      nestedUser.email ||
      state.operatorEmail ||
      state.generatedBy
  );

  if (email.includes('@')) {
    const localPart = email.split('@')[0];

    if (localPart.toLowerCase() === 'wilsonkhanyezi') {
      return 'Wilson Khanyezi';
    }

    const emailName = titleCaseHumanName(localPart);

    if (emailName && emailName.split(' ').length >= 2) {
      return emailName;
    }
  }

  return directName || state.generatedBy || 'Verified Wilsy Operator';
}

/**
 * @function replaceGeneratedBySlugRows
 * @description Rewrites proof-pack generated-by rows so audit PDFs show human accountability instead of system slugs.
 * @param {unknown[]} rows - Proof rows.
 * @param {string} generatedByName - Human generated-by name.
 * @returns {unknown[]} Rows with generated-by values corrected.
 * @collaboration CRM Proof Pack evidence rows, PDF document control, and operator accountability controls.
 */
function replaceGeneratedBySlugRows(rows = [], generatedByName = '') {
  if (!Array.isArray(rows)) {
    return [];
  }

  return rows.map((row) => {
    if (Array.isArray(row)) {
      const label = textValue(row[0]).toLowerCase();

      if (
        label === 'generated by' ||
        label === 'generatedby' ||
        label === 'operator' ||
        label === 'generated by:'
      ) {
        return [row[0], generatedByName];
      }

      return row;
    }

    if (row && typeof row === 'object') {
      const label = textValue(row.label || row.title || row.key || row.name).toLowerCase();

      if (
        label === 'generated by' ||
        label === 'generatedby' ||
        label === 'operator' ||
        label === 'generated by:'
      ) {
        return {
          ...row,
          value: generatedByName,
          detail:
            row.detail && textValue(row.detail).toLowerCase() !== 'wilsy-operator'
              ? row.detail
              : generatedByName,
        };
      }

      return row;
    }

    return row;
  });
}

/**
 * @function buildState
 * @description Builds normalized render state from verified request identity and proof context.
 * @param {object} identity - Verified artifact identity.
 * @param {object} proof - Forensic proof context.
 * @returns {object} Render state.
 * @collaboration Bridges request verification into the enterprise renderer.
 */
function buildState(identity = {}, proof = {}) {
  const data = identity.data || identity.payload || {};
  const type = textValue(identity.type || identity.artifactType || data.type || 'artifact');
  const title = textValue(identity.title || data.title || titleFromType(type));

  return {
    type,
    title,
    tenantId: textValue(identity.tenantId || data.tenantId || 'MASTER'),
    issuingEntity: textValue(data.issuingEntity || identity.issuingEntity || 'Wilsy (Pty) Ltd'),
    counterparty: textValue(
      data.counterparty || identity.counterparty || 'Counterparty To Be Completed'
    ),
    generatedBy: resolveHumanGeneratedByName({
      proofPack: data.crmProofPack || data.proofPackSections || {},
      identity,
      state: { generatedBy: data.generatedBy },
    }),
    effectiveDate: textValue(data.effectiveDate || new Date().toISOString().slice(0, 10)),
    version: textValue(data.version || 'WILSY-OS-ARTIFACT-v2.1-ENTERPRISE'),
    jurisdiction: textValue(data.jurisdiction || 'Republic of South Africa'),
    sourcePosture: textValue(proof.sourcePosture || data.sourcePosture || 'SOURCE_REPAIR_REQUIRED'),
    traceId: textValue(proof.traceId || identity.traceId || 'TRACE-PENDING'),
    merkleRoot: textValue(proof.merkleRoot || identity.merkleRoot || 'MERKLE-PENDING'),
    sha3: textValue(proof.serverSeal || proof.sha3 || identity.requestProof || 'LOCAL-PROOF'),
    generatedAt: new Date().toISOString(),
  };
}

/**
 * @function drawLogo
 * @description Draws the Wilsy logo optically centered inside the enterprise header badge.
 * @param {PDFDocument} doc - PDF document.
 * @returns {void}
 * @collaboration Ensures every generated artifact has precise institutional branding.
 */
function drawLogo(doc) {
  const logoPath = findLogoPath();
  const boxX = 60;
  const boxY = 50;
  const boxSize = 62;
  const logoWidth = 44;
  const logoHeight = 50;

  doc.roundedRect(boxX, boxY, boxSize, boxSize, 5).fill('#FFFFFF');

  if (logoPath) {
    try {
      doc.image(logoPath, boxX + (boxSize - logoWidth) / 2, boxY + (boxSize - logoHeight) / 2, {
        fit: [logoWidth, logoHeight],
      });
      return;
    } catch {
      // fallback below
    }
  }

  doc
    .fillColor(BRAND.black)
    .font('Helvetica-Bold')
    .fontSize(17)
    .text('WO', boxX + 18, boxY + 24, { width: 26, align: 'center', lineBreak: false });
}

/**
 * @function drawHeader
 * @description Draws a non-overlapping Wilsy OS enterprise header with logo and accurate pagination.
 * @param {PDFDocument} doc - PDF document.
 * @param {object} state - Render state.
 * @param {number} pageNumber - Page number.
 * @param {number} totalPages - Total pages.
 * @returns {void}
 * @collaboration Produces tenant-facing header quality for legal, HR, finance and invoice artifacts.
 */
function drawHeader(doc, state, pageNumber, totalPages) {
  doc.save();

  doc.rect(42, 34, 512, 126).fill(BRAND.black);
  doc.rect(42, 160, 512, 5).fill(BRAND.gold);

  drawLogo(doc);

  const title = textValue(state.title || 'Wilsy OS Artifact').toUpperCase();
  const titleSize = title.length > 48 ? 14.5 : title.length > 34 ? 17 : title.length > 22 ? 20 : 22;

  doc
    .fillColor(BRAND.gold)
    .font('Helvetica-Bold')
    .fontSize(8.5)
    .text(
      isWilsyKnowledgeBaseState(state)
        ? 'WILSY OS KNOWLEDGE BASE ARTIFACT'
        : 'WILSY OS ENTERPRISE ARTIFACT',
      140,
      52,
      { width: 300, lineBreak: false }
    );

  doc
    .fillColor('#FFFFFF')
    .font('Helvetica-Bold')
    .fontSize(titleSize)
    .text(title, 140, 72, { width: 300, lineGap: 0 });

  doc
    .fillColor(BRAND.ivory)
    .font('Helvetica')
    .fontSize(7)
    .text('Authority • Review • Execution • Forensic Proof • Source-Aware Control', 140, 134, {
      width: 338,
      lineBreak: false,
    });

  doc
    .fillColor(BRAND.gold)
    .font('Helvetica-Bold')
    .fontSize(8)
    .text('VERIFIED', 424, 54, { width: 66, align: 'right', lineBreak: false });

  doc
    .fillColor('#FFFFFF')
    .font('Helvetica-Bold')
    .fontSize(8)
    .text(`PAGE ${pageNumber}/${totalPages}`, 494, 54, {
      width: 48,
      align: 'right',
      lineBreak: false,
    });

  doc.restore();
}

/**
 * @function drawFooter
 * @description Draws a non-overlapping proof footer.
 * @param {PDFDocument} doc - PDF document.
 * @param {object} state - Render state.
 * @returns {void}
 * @collaboration Prevents forensic proof collisions in production tenant-facing documents.
 */
function drawFooter(doc, state) {
  doc.save();

  doc.moveTo(PAGE.left, 762).lineTo(543, 762).strokeColor(BRAND.line).lineWidth(0.6).stroke();

  doc
    .fillColor(BRAND.muted)
    .font('Helvetica')
    .fontSize(6.2)
    .text(
      'Legally non-final until reviewed and approved. Retain with the Wilsy OS proof trail.',
      PAGE.left,
      773,
      {
        width: 282,
        lineBreak: false,
      }
    );

  doc
    .fillColor(BRAND.black)
    .font('Helvetica-Bold')
    .fontSize(6.2)
    .text('DIRECTOR - WILSON KHANYEZI', PAGE.left, 792, { width: 282, lineBreak: false });

  doc
    .fillColor(BRAND.gold)
    .font('Helvetica-Bold')
    .fontSize(5.4)
    .text(`TRACE ${compactProof(state.traceId)}`, 344, 772, {
      width: 199,
      align: 'right',
      lineBreak: false,
    });

  doc
    .fillColor(BRAND.gold)
    .font('Helvetica-Bold')
    .fontSize(5.4)
    .text(`MERKLE ${compactProof(state.merkleRoot)}`, 344, 782, {
      width: 199,
      align: 'right',
      lineBreak: false,
    });

  doc
    .fillColor(BRAND.muted)
    .font('Helvetica')
    .fontSize(5.3)
    .text(`SHA3 ${compactProof(state.sha3)}`, 344, 792, {
      width: 199,
      align: 'right',
      lineBreak: false,
    });

  doc
    .fillColor(BRAND.muted)
    .font('Helvetica')
    .fontSize(5.3)
    .text(state.sourcePosture, 344, 802, { width: 199, align: 'right', lineBreak: false });

  doc.restore();
}

/**
 * @function ensureSpace
 * @description Adds a page when the remaining content area is too small.
 * @param {PDFDocument} doc - PDF document.
 * @param {object} cursor - Cursor state.
 * @param {number} required - Required height.
 * @returns {void}
 * @collaboration Maintains professional page flow and protects the footer zone.
 */
function ensureSpace(doc, cursor, required) {
  cursor = normalizeEnterprisePdfCursor(cursor, PAGE.top);
  if (cursor.y + required <= PAGE.bottom) return;

  doc.addPage();
  cursor.y = PAGE.top;
}

/**
 * @function writeParagraph
 * @description Writes a numbered paragraph and updates the cursor.
 * @param {PDFDocument} doc - PDF document.
 * @param {object} cursor - Cursor state.
 * @param {string} paragraph - Paragraph text.
 * @param {number} index - Paragraph index.
 * @returns {void}
 * @collaboration Produces readable legal instrument body copy.
 */
function writeParagraph(doc, cursor, paragraph, index) {
  cursor = normalizeEnterprisePdfCursor(cursor, PAGE.top);
  const paragraphWidth = PAGE.contentWidth - 32;
  const paragraphHeight = doc.heightOfString(textValue(paragraph), {
    width: paragraphWidth,
    lineGap: 2.8,
  });

  ensureSpace(doc, cursor, Math.max(34, paragraphHeight + 16));

  doc
    .fillColor(BRAND.gold)
    .font('Helvetica-Bold')
    .fontSize(8)
    .text(`${index + 1}.`, PAGE.left + 8, cursor.y + 1, { width: 18, lineBreak: false });

  doc
    .fillColor(BRAND.black)
    .font('Helvetica')
    .fontSize(8.8)
    .text(textValue(paragraph), PAGE.left + 30, cursor.y, {
      width: paragraphWidth,
      lineGap: 2.8,
    });

  cursor.y = doc.y + 10;

  return cursor;
}

/**
 * @function drawSection
 * @description Draws a controlled enterprise section.
 * @param {PDFDocument} doc - PDF document.
 * @param {object} cursor - Cursor state.
 * @param {object} section - Section definition.
 * @returns {void}
 * @collaboration Creates dense but readable enterprise legal and business artifacts.
 */
function drawSection(doc, cursor, section) {
  cursor = normalizeEnterprisePdfCursor(cursor, PAGE.top);
  ensureSpace(doc, cursor, 72);

  doc
    .fillColor(BRAND.black)
    .font('Helvetica-Bold')
    .fontSize(11.2)
    .text(textValue(section.title).toUpperCase(), PAGE.left, cursor.y, {
      width: PAGE.contentWidth,
    });

  cursor.y = doc.y + 14;

  const paragraphs = Array.isArray(section.paragraphs) ? section.paragraphs : [];
  paragraphs.forEach((paragraph, index) => {
    cursor = writeParagraph(doc, cursor, paragraph, index);
  });

  cursor.y += 10;

  return cursor;
}

/**
 * @function resolveCrmProofPackFromIdentity
 * @description Resolves CRM Proof Pack evidence from the already-adapted enterprise identity.
 * @param {object} identity Enterprise identity.
 * @returns {object} CRM proof pack evidence object.
 * @collaboration businessArtifactPdfController, CRM proof adapter, and enterprise PDF renderer.
 */
function resolveCrmProofPackFromIdentity(identity = {}) {
  const data = identity.data || {};
  const payload = identity.payload || {};
  const payloadData = identity.payloadData || {};

  return (
    identity.crmProofPack ||
    identity.proofPackSections ||
    payloadData.crmProofPack ||
    payloadData.proofPackSections ||
    payload.crmProofPack ||
    payload.proofPackSections ||
    data.crmProofPack ||
    data.proofPackSections ||
    {}
  );
}

/**
 * @function hasCrmProofPackEvidence
 * @description Detects whether a CRM proof pack contains exportable evidence rows.
 * @param {object} proofPack CRM proof pack object.
 * @returns {boolean} True when CRM evidence rows exist.
 * @collaboration CRM Proof Pack adapter and enterprise PDF section routing.
 */
function hasCrmProofPackEvidence(proofPack = {}) {
  return Boolean(
    Array.isArray(proofPack.proofSummaryRows) ||
    Array.isArray(proofPack.authoritySealRows) ||
    Array.isArray(proofPack.proofChecks) ||
    Array.isArray(proofPack.operationalTimeline) ||
    Array.isArray(proofPack.scopedRecords) ||
    Array.isArray(proofPack.metricsRows)
  );
}

/**
 * @function hydrateCrmProofPackState
 * @description Adds CRM Proof Pack evidence to the normal enterprise render state without replacing buildState.
 * @param {object} state Existing enterprise render state.
 * @param {object} identity Enterprise identity.
 * @param {object} proof Forensic proof context.
 * @returns {object} Hydrated render state.
 * @collaboration Preserves branded/security chrome while replacing only CRM payload content.
 */
function hydrateCrmProofPackState(state = {}, identity = {}, proof = {}) {
  const proofPack = resolveCrmProofPackFromIdentity(identity);

  if (!hasCrmProofPackEvidence(proofPack)) {
    return state;
  }

  const tenantId = textValue(proofPack.tenantId || identity.tenantId || state.tenantId || 'MASTER');
  const generatedBy = resolveHumanGeneratedByName({ proofPack, identity, state });
  const operatorEmail = textValue(
    proofPack.operatorEmail ||
      proofPack.email ||
      identity.userEmail ||
      identity.email ||
      identity.user?.email ||
      state.operatorEmail ||
      ''
  );

  const sourcePosture = textValue(
    proofPack.sourcePosture ||
      (identity.sourcePosture && identity.sourcePosture !== 'SOURCE_REPAIR_REQUIRED'
        ? identity.sourcePosture
        : '') ||
      (proof.sourcePosture && proof.sourcePosture !== 'SOURCE_REPAIR_REQUIRED'
        ? proof.sourcePosture
        : '') ||
      'SOURCE_LIVE'
  );

  return {
    ...state,
    tenantId,
    counterparty: textValue(proofPack.counterparty || tenantId),
    generatedBy,
    operatorEmail,
    sourcePosture,
    generatedAt: textValue(proofPack.generatedAt || identity.generatedAt || state.generatedAt),
    crmProofPack: proofPack,
    hasCrmProofPack: true,
    proofSummaryRows: proofPack.proofSummaryRows || [],
    authoritySealRows: replaceGeneratedBySlugRows(proofPack.authoritySealRows || [], generatedBy),
    proofChecks: proofPack.proofChecks || [],
    operationalTimeline: proofPack.operationalTimeline || [],
    scopedRecords: proofPack.scopedRecords || [],
    metricsRows: proofPack.metricsRows || [],
  };
}

/**
 * @function isCrmProofPackState
 * @description Detects CRM Proof Pack state inside the enterprise branded PDF renderer.
 * @param {object} state Render state.
 * @returns {boolean} True when CRM proof evidence is present.
 * @collaboration businessArtifactPdfController, CRM proof adapter, and Wilsy enterprise PDF shell.
 */
function isCrmProofPackState(state = {}) {
  return Boolean(state.hasCrmProofPack);
}

/**
 * @function normalizeCrmProofPackText
 * @description Converts CRM proof evidence values into compact PDF-safe text.
 * @param {unknown} value Source value.
 * @returns {string} PDF-safe text.
 * @collaboration CRM evidence rows and enterprise PDF section writer.
 */
function normalizeCrmProofPackText(value = '') {
  if (Array.isArray(value)) {
    return value
      .map((item) => normalizeCrmProofPackText(item))
      .filter(Boolean)
      .join(' - ');
  }

  if (value && typeof value === 'object') {
    return Object.entries(value)
      .map(([key, itemValue]) => `${textValue(key)}: ${normalizeCrmProofPackText(itemValue)}`)
      .filter(Boolean)
      .join(' - ');
  }

  return textValue(value);
}

/**
 * @function normalizeCrmProofPackRowsForPdf
 * @description Converts CRM Proof Pack rows into narrative bullets for the branded renderer.
 * @param {unknown} rows Source rows.
 * @returns {string[]} PDF paragraph rows.
 * @collaboration CRM proof rows, story sections, and Wilsy enterprise PDF renderer.
 */
function normalizeCrmProofPackRowsForPdf(rows = []) {
  if (!Array.isArray(rows)) {
    return [];
  }

  return rows
    .map((row) => {
      if (Array.isArray(row)) {
        return `${textValue(row[0])}: ${normalizeCrmProofPackText(row[1])}`;
      }

      if (row && typeof row === 'object') {
        const label = textValue(row.label || row.title || row.key || row.name || 'Evidence');
        const detail = normalizeCrmProofPackText(
          [row.status, row.reason, row.value, row.detail].filter(Boolean)
        );

        return detail ? `${label}: ${detail}` : label;
      }

      return normalizeCrmProofPackText(row);
    })
    .filter(Boolean);
}

/**
 * @function getCrmProofPackSections
 * @description Builds CRM Proof Pack sections while preserving the Wilsy enterprise PDF chrome.
 * @param {object} state Render state.
 * @returns {Array<object>} CRM-specific artifact sections.
 * @collaboration Replaces generic legal artifact payload with CRM proof narrative.
 */
function getCrmProofPackSections(state = {}) {
  return [
    {
      title: '1. PROOF SUMMARY AND OPERATING CONTEXT',
      paragraphs: [
        'This Lead Evidence Ledger Proof Pack records the saved-view proof, ledger access decision, export authority, source-route posture, membership overrides and run receipt that support the CRM operating decision.',
        ...normalizeCrmProofPackRowsForPdf(state.proofSummaryRows),
      ],
    },
    {
      title: '2. TENANT, OPERATOR AND AUTHORITY SEALS',
      paragraphs: [
        `Tenant: ${state.tenantId}`,
        `Generated by: ${state.generatedBy}`,
        `Operator email: ${state.operatorEmail}`,
        `Source posture: ${state.sourcePosture}`,
        ...normalizeCrmProofPackRowsForPdf(state.authoritySealRows),
      ],
    },
    {
      title: '3. PROOF CHECKS, CONTROLS AND EXCEPTIONS',
      paragraphs: [
        'The checks below show what was validated before this proof pack was exported.',
        ...normalizeCrmProofPackRowsForPdf(state.proofChecks),
      ],
    },
    {
      title: '4. OPERATIONAL TIMELINE AND SCOPED RECORDS',
      paragraphs: [
        'The timeline and scoped-record evidence below explain what happened, what data was in scope, and how the proof can be reconstructed.',
        ...normalizeCrmProofPackRowsForPdf(state.operationalTimeline),
        ...normalizeCrmProofPackRowsForPdf(state.scopedRecords),
      ],
    },
    {
      title: '5. METRICS AND DECISION SUPPORT',
      paragraphs: [
        'The metrics below summarize the exported CRM proof result.',
        ...normalizeCrmProofPackRowsForPdf(state.metricsRows),
      ],
    },
  ];
}

/**
 * @function getCrmProofPackScheduleSections
 * @description Builds CRM Proof Pack appendix sections for the branded enterprise schedule area.
 * @param {object} state Render state.
 * @returns {Array<object>} CRM proof schedule sections.
 * @collaboration Preserves forensic appendix posture without showing generic missing-source legal fields.
 */
function getCrmProofPackScheduleSections(state = {}) {
  return [
    {
      title: 'SCHEDULE A - CRM PROOF EVIDENCE LEDGER',
      paragraphs: [
        ...normalizeCrmProofPackRowsForPdf(state.proofSummaryRows),
        ...normalizeCrmProofPackRowsForPdf(state.authoritySealRows),
        ...normalizeCrmProofPackRowsForPdf(state.proofChecks),
      ],
    },
    {
      title: 'SCHEDULE B - FORENSIC PROOF APPENDIX',
      paragraphs: [
        `Trace ID: ${state.traceId}`,
        `Merkle Root: ${state.merkleRoot}`,
        `SHA3 / Seal: ${state.sha3}`,
        `Source Posture: ${state.sourcePosture}`,
        `Generated At: ${state.generatedAt}`,
        'This appendix supports audit reconstruction, version comparison, dispute response, investor diligence and internal control review.',
      ],
    },
  ];
}

/**
 * @function getNdaSections
 * @description Returns deeper enterprise NDA clauses.
 * @param {object} state - Render state.
 * @returns {Array<object>} NDA sections.
 * @collaboration Upgrades NDA output beyond shallow prototype clauses.
 */
function getNdaSections(state) {
  return [
    {
      title: '1. Instrument Status, Parties and Effective Date',
      paragraphs: [
        `This Non-Disclosure Agreement is issued by ${state.issuingEntity} for use with ${state.counterparty}. It is generated through Wilsy OS as a source-aware legal artifact and remains subject to final business, legal and authority review before external reliance.`,
        `The effective date is ${state.effectiveDate}. Each party must ensure the person signing has authority to bind the relevant entity, and any missing registration, address, representative, schedule or commercial field must remain visible until verified.`,
      ],
    },
    {
      title: '2. Definitions',
      paragraphs: [
        '“Confidential Information” means all information disclosed or made available in connection with the permitted purpose, whether oral, written, electronic, visual, technical, operational, commercial, financial, legal, regulatory, product, source-code, architecture, security, client, tenant, pricing, roadmap, investor, employee, procurement or forensic information.',
        '“Representatives” means directors, officers, employees, contractors, professional advisers, auditors, investors, funders and affiliates who have a need to know and are bound by confidentiality obligations no less protective than this agreement.',
      ],
    },
    {
      title: '3. Permitted Purpose and Use Restrictions',
      paragraphs: [
        'The receiving party may use Confidential Information only for the authorised business purpose recorded in the applicable engagement, evaluation, diligence, onboarding, procurement, integration or commercial negotiation record.',
        'The receiving party must not copy, reverse engineer, decompile, benchmark, publish, train models on, scrape, exploit, commercialise, disclose or use Confidential Information for any competing, unauthorised, unlawful or personal purpose.',
      ],
    },
    {
      title: '4. Security Standard and Incident Duties',
      paragraphs: [
        'The receiving party must protect Confidential Information using administrative, technical and organisational controls appropriate to the sensitivity of the information, including access limitation, secure storage, device protection, encryption where appropriate, auditability and need-to-know distribution.',
        'Any suspected unauthorised access, disclosure, loss, compromise, ransomware event, credential exposure, insider risk or legal demand must be notified promptly with sufficient detail to support containment, investigation, regulatory assessment and remediation.',
      ],
    },
    {
      title: '5. Remedies, POPIA and Survival',
      paragraphs: [
        'The parties acknowledge that unauthorised disclosure or misuse may cause irreparable harm for which damages may be inadequate. The disclosing party may seek urgent interdictory, injunctive or equitable relief without prejudice to other remedies.',
        `Where Confidential Information includes personal information or regulated records, the parties must comply with applicable privacy, data protection, retention and breach notification duties, including POPIA where applicable in the ${state.jurisdiction}.`,
      ],
    },
  ];
}

/**
 * @function getGenericSections
 * @description Returns enterprise fallback sections for non-NDA artifacts.
 * @param {object} state - Render state.
 * @returns {Array<object>} Generic enterprise sections.
 * @collaboration Gives every catalog artifact a serious baseline until type-specific libraries are completed.
 */
function getGenericSections(state) {
  return [
    {
      title: '1. Executive Purpose and Operating Context',
      paragraphs: [
        `${state.title} is generated for ${state.issuingEntity} under Wilsy OS artifact authority. It supports executive decision-making, operational execution, compliance evidence, commercial negotiation or controlled business workflow completion.`,
        'This artifact must be reviewed with its source records, approvals, schedules, attachments and Wilsy OS proof trail.',
      ],
    },
    {
      title: '2. Parties, Owners and Authority',
      paragraphs: [
        `The issuing entity is ${state.issuingEntity}. The counterparty, tenant, employee, supplier, client or stakeholder is ${state.counterparty}.`,
        'Only authorised users may generate, approve, circulate, amend, execute or rely on this artifact. Missing approval, signature or source fields must remain visible until verified.',
      ],
    },
    {
      title: '3. Scope, Controls and Exceptions',
      paragraphs: [
        'The artifact records the business purpose, obligations, decision posture, control evidence and operational assumptions reflected in connected Wilsy OS source systems.',
        'Exceptions require documented approval, accountable owner, expiry date and remediation path.',
      ],
    },
    {
      title: '4. Forensic Proof and Retention',
      paragraphs: [
        `Trace identifier: ${state.traceId}. Merkle root: ${compactProof(state.merkleRoot)}. Source posture: ${state.sourcePosture}.`,
        'External distribution should occur through the Wilsy OS document vault or an approved connector so access logs, version history, proof verification and revocation can be reconstructed.',
      ],
    },
  ];
}

/**
 * @function resolveWilsyKnowledgeBaseFromIdentity
 * @description Resolves a Wilsy knowledge-base/playbook payload from the enterprise PDF identity envelope.
 * @param {object} identity Enterprise artifact identity.
 * @returns {object} Knowledge-base payload candidate.
 * @collaboration FG108O3B2, Wilsy AI playbook exports, and the active enterprise PDF renderer.
 */
function resolveWilsyKnowledgeBaseFromIdentity(identity = {}) {
  const data = identity.data || {};
  const payload = identity.payload || {};
  const payloadData = identity.payloadData || {};
  const metadata = identity.metadata || payload.metadata || data.metadata || {};

  return (
    identity.knowledgeBase ||
    identity.playbook ||
    identity.playbookPayload ||
    payloadData.knowledgeBase ||
    payloadData.playbook ||
    payloadData.playbookPayload ||
    payload.knowledgeBase ||
    payload.playbook ||
    payload.playbookPayload ||
    data.knowledgeBase ||
    data.playbook ||
    data.playbookPayload || {
      type:
        identity.type ||
        identity.artifactType ||
        payloadData.type ||
        payloadData.artifactType ||
        payload.type ||
        payload.artifactType ||
        data.type ||
        metadata.type,
      artifactType:
        identity.artifactType ||
        payloadData.artifactType ||
        payload.artifactType ||
        data.artifactType ||
        metadata.artifactType,
      title: identity.title || payloadData.title || payload.title || data.title || metadata.title,
      subtitle: payloadData.subtitle || payload.subtitle || data.subtitle || metadata.subtitle,
      summary: payloadData.summary || payload.summary || data.summary || metadata.summary,
      markdown: payloadData.markdown || payload.markdown || data.markdown || metadata.markdown,
      sections:
        payloadData.playbookSections ||
        payloadData.knowledgeBaseSections ||
        payloadData.sections ||
        payload.sections ||
        data.sections,
      metrics: payloadData.metrics || payload.metrics || data.metrics,
      tenantId:
        identity.tenantId ||
        payloadData.tenantId ||
        payload.tenantId ||
        data.tenantId ||
        metadata.tenantId,
      generatedBy:
        identity.generatedBy ||
        identity.userEmail ||
        identity.email ||
        payloadData.generatedBy ||
        payload.generatedBy ||
        data.generatedBy ||
        metadata.generatedBy,
      generatedAt:
        identity.generatedAt ||
        payloadData.generatedAt ||
        payloadData.timestamp ||
        payload.generatedAt ||
        data.generatedAt ||
        metadata.generatedAt ||
        metadata.timestamp,
      sourcePosture:
        identity.sourcePosture ||
        payloadData.sourcePosture ||
        payload.sourcePosture ||
        data.sourcePosture ||
        metadata.sourcePosture,
    }
  );
}

/**
 * @function isWilsyKnowledgeBaseCandidate
 * @description Detects Wilsy knowledge-base/playbook artifacts before the generic legal renderer is selected.
 * @param {object} candidate Knowledge-base candidate.
 * @returns {boolean} True when the artifact is a Wilsy knowledge-base/playbook export.
 * @collaboration FG108O3B2 renderer routing and /api/generate/pdf knowledge-base exports.
 */
function isWilsyKnowledgeBaseCandidate(candidate = {}) {
  const values = [
    candidate.type,
    candidate.artifactType,
    candidate.templateType,
    candidate.title,
    candidate.subtitle,
  ]
    .map((value) => textValue(value).toUpperCase())
    .filter(Boolean);

  return values.some(
    (value) =>
      value.includes('WILSY_AI_INLINE_COMMAND_PLAYBOOK_FG108') ||
      value.includes('WILSY KNOWLEDGE BASE') ||
      value.includes('KNOWLEDGE_BASE') ||
      value.includes('KNOWLEDGE BASE') ||
      value.includes('PLAYBOOK')
  );
}

/**
 * @function normalizeWilsyKnowledgeBaseText
 * @description Converts knowledge-base payload values into safe enterprise-renderer paragraph text.
 * @param {unknown} value Source value.
 * @returns {string} PDF-safe text.
 * @collaboration FG108O3B2 knowledge-base sections and Wilsy enterprise PDF text flow.
 */
function normalizeWilsyKnowledgeBaseText(value = '') {
  if (Array.isArray(value)) {
    return value
      .map((item) => normalizeWilsyKnowledgeBaseText(item))
      .filter(Boolean)
      .join(' - ');
  }

  if (value && typeof value === 'object') {
    return Object.entries(value)
      .map(([key, itemValue]) => `${textValue(key)}: ${normalizeWilsyKnowledgeBaseText(itemValue)}`)
      .filter(Boolean)
      .join(' - ');
  }

  return textValue(value);
}

/**
 * @function normalizeWilsyKnowledgeBaseSection
 * @description Converts a playbook section payload into the enterprise renderer section contract.
 * @param {unknown} section Source section.
 * @param {number} index Section index.
 * @returns {object} Enterprise renderer section.
 * @collaboration FG108O3B2 markdown/section payloads and drawSection compatibility.
 */
function normalizeWilsyKnowledgeBaseSection(section = {}, index = 0) {
  if (typeof section === 'string') {
    return {
      title: `SECTION ${index + 1}`,
      paragraphs: [normalizeWilsyKnowledgeBaseText(section)],
    };
  }

  const title = normalizeWilsyKnowledgeBaseText(
    section.title || section.heading || section.label || `Section ${index + 1}`
  );

  const body =
    section.paragraphs ||
    section.body ||
    section.summary ||
    section.content ||
    section.description ||
    '';

  const paragraphs = Array.isArray(body)
    ? body.map((item) => normalizeWilsyKnowledgeBaseText(item)).filter(Boolean)
    : normalizeWilsyKnowledgeBaseText(body)
        .split(/\n+/)
        .map((item) => item.trim())
        .filter(Boolean);

  return {
    title,
    paragraphs: paragraphs.length
      ? paragraphs
      : ['Wilsy OS knowledge-base section retained for controlled review.'],
  };
}

/**
 * @function resolveWilsyKnowledgeBaseMarkdownSections
 * @description Converts markdown headings into enterprise renderer sections when structured sections are absent.
 * @param {string} markdown Playbook markdown.
 * @returns {Array<object>} Enterprise renderer sections.
 * @collaboration FG108O3B2 markdown payloads and investor-readable PDF sections.
 */
function resolveWilsyKnowledgeBaseMarkdownSections(markdown = '') {
  const value = textValue(markdown);
  if (!value) return [];

  return value
    .split(/\n(?=##\s+)/)
    .map((chunk) => chunk.trim())
    .filter(Boolean)
    .slice(0, 14)
    .map((chunk, index) => {
      const lines = chunk
        .split(/\n+/)
        .map((line) => line.trim())
        .filter(Boolean);
      const title = textValue(lines.shift() || `Section ${index + 1}`).replace(/^#+\s*/, '');
      const paragraphs = lines
        .join(' ')
        .split(/\s{2,}|---/)
        .map((line) => textValue(line))
        .filter(Boolean)
        .slice(0, 8);

      return {
        title,
        paragraphs: paragraphs.length
          ? paragraphs
          : ['Wilsy OS knowledge-base content retained for review.'],
      };
    });
}

/**
 * @function hydrateWilsyKnowledgeBaseState
 * @description Adds Wilsy knowledge-base playbook content to the enterprise render state without bypassing the branded PDF engine.
 * @param {object} state Existing render state.
 * @param {object} identity Enterprise artifact identity.
 * @param {object} proof Forensic proof context.
 * @returns {object} Hydrated render state.
 * @collaboration FG108O3B2, streamEnterpriseArtifactPdf, and Wilsy AI knowledge-base exports.
 */
function hydrateWilsyKnowledgeBaseState(state = {}, identity = {}, proof = {}) {
  const knowledgeBase = resolveWilsyKnowledgeBaseFromIdentity(identity);

  if (!isWilsyKnowledgeBaseCandidate(knowledgeBase)) {
    return state;
  }

  const structuredSections =
    Array.isArray(knowledgeBase.sections) && knowledgeBase.sections.length > 0
      ? knowledgeBase.sections.map((section, index) =>
          normalizeWilsyKnowledgeBaseSection(section, index)
        )
      : resolveWilsyKnowledgeBaseMarkdownSections(knowledgeBase.markdown);

  return {
    ...state,
    title: textValue(
      knowledgeBase.title || state.title || 'WILSY OS AI INLINE COMMAND PLAYBOOK - FG108'
    ),
    type: textValue(
      knowledgeBase.type ||
        knowledgeBase.artifactType ||
        state.type ||
        'WILSY_AI_INLINE_COMMAND_PLAYBOOK_FG108'
    ),
    tenantId: textValue(knowledgeBase.tenantId || state.tenantId || 'wilsy-sovereign-root'),
    counterparty: textValue(knowledgeBase.tenantId || state.tenantId || 'wilsy-sovereign-root'),
    generatedBy: textValue(knowledgeBase.generatedBy || state.generatedBy || 'Wilson Khanyezi'),
    generatedAt: textValue(
      knowledgeBase.generatedAt || state.generatedAt || new Date().toISOString()
    ),
    sourcePosture: textValue(knowledgeBase.sourcePosture || 'KNOWLEDGE_BASE_VERIFIED'),
    version: textValue(knowledgeBase.version || 'WILSY-OS-KNOWLEDGE-BASE-FG108-v1.0'),
    hasWilsyKnowledgeBase: true,
    wilsyKnowledgeBase: knowledgeBase,
    knowledgeBaseSections: structuredSections.length
      ? structuredSections
      : [
          {
            title: 'Executive Summary',
            paragraphs: [
              textValue(
                knowledgeBase.summary ||
                  'Wilsy OS knowledge-base playbook generated through the governed enterprise PDF renderer.'
              ),
            ],
          },
        ],
  };
}

/**
 * @function isWilsyKnowledgeBaseState
 * @description Detects a hydrated Wilsy knowledge-base state inside the enterprise PDF renderer.
 * @param {object} state Render state.
 * @returns {boolean} True when the render state is a knowledge-base playbook.
 * @collaboration FG108O3B2 renderer routing and generic legal-section suppression.
 */
function isWilsyKnowledgeBaseState(state = {}) {
  return Boolean(state.hasWilsyKnowledgeBase);
}

/**
 * @function getWilsyKnowledgeBaseSections
 * @description Builds primary Wilsy knowledge-base sections while preserving enterprise PDF chrome.
 * @param {object} state Render state.
 * @returns {Array<object>} Primary knowledge-base sections.
 * @collaboration FG108O3B2 playbook content and buildSections routing.
 */
function getWilsyKnowledgeBaseSections(state = {}) {
  return [
    {
      title: '1. KNOWLEDGE BASE PURPOSE AND OPERATING CONTEXT',
      paragraphs: [
        'This artifact is a Wilsy OS knowledge-base playbook for investor review, user enablement, engineering continuity and controlled product governance.',
        `Tenant: ${state.tenantId}`,
        `Generated by: ${state.generatedBy}`,
        `Source posture: ${state.sourcePosture}`,
      ],
    },
    ...state.knowledgeBaseSections,
  ];
}

/**
 * @function getWilsyKnowledgeBaseScheduleSections
 * @description Builds non-legal appendix sections for Wilsy knowledge-base artifacts.
 * @param {object} state Render state.
 * @returns {Array<object>} Knowledge-base appendix sections.
 * @collaboration FG108O3B2 proof appendix, investor diligence, and future engineer handoff.
 */
function getWilsyKnowledgeBaseScheduleSections(state = {}) {
  return [
    {
      title: 'APPENDIX A - KNOWLEDGE BASE PROOF CONTEXT',
      paragraphs: [
        `Trace ID: ${state.traceId}`,
        `Merkle root: ${compactProof(state.merkleRoot)}`,
        `Source posture: ${state.sourcePosture}`,
        `Route: /api/generate/pdf`,
        'This appendix supports reconstruction, version comparison, investor diligence, user training and future engineering continuity.',
      ],
    },
  ];
}

// WILSY_FG108O3B2_ENTERPRISE_KNOWLEDGE_RENDERER

/**
 * @function buildSections
 * @description Selects the appropriate clause library for the artifact type.
 * @param {object} state - Render state.
 * @returns {Array<object>} Sections.
 * @collaboration Provides a safe expansion path for legal, HR, finance and operational documents.
 */
function buildSections(state) {
  if (isWilsyKnowledgeBaseState(state)) {
    return getWilsyKnowledgeBaseSections(state);
  }

  if (isCrmProofPackState(state)) {
    return getCrmProofPackSections(state);
  }

  const type = state.type.toLowerCase();

  if (type.includes('nda') || type.includes('non-disclosure')) {
    return getNdaSections(state);
  }

  return getGenericSections(state);
}

/**
 * @function drawDocumentControl
 * @description Draws the document control section.
 * @param {PDFDocument} doc - PDF document.
 * @param {object} cursor - Cursor state.
 * @param {object} state - Render state.
 * @returns {void}
 * @collaboration Provides tenant-facing document identity, source posture and proof metadata.
 */
function drawDocumentControl(doc, cursor, state) {
  cursor = normalizeEnterprisePdfCursor(cursor, PAGE.top);
  doc
    .fillColor(BRAND.black)
    .font('Helvetica-Bold')
    .fontSize(15)
    .text('DOCUMENT CONTROL', PAGE.left, cursor.y);
  cursor.y = doc.y + 22;

  const rows = [
    ['Issuing Entity', state.issuingEntity],
    ['Counterparty / Tenant', state.counterparty],
    ['Effective Date', state.effectiveDate],
    ['Generated By', state.generatedBy],
    ['Version', state.version],
    ['Jurisdiction', state.jurisdiction],
    ['Source Posture', state.sourcePosture],
    ['Trace ID', state.traceId],
    ['Merkle Root', compactProof(state.merkleRoot)],
  ];

  rows.forEach((row, index) => {
    const y = cursor.y + index * 21;
    doc.rect(PAGE.left, y, PAGE.contentWidth, 20).fill(index % 2 === 0 ? '#FFFFFF' : BRAND.band);
    doc
      .fillColor(BRAND.muted)
      .font('Helvetica-Bold')
      .fontSize(6.8)
      .text(row[0].toUpperCase(), PAGE.left + 10, y + 7, { width: 160, lineBreak: false });
    doc
      .fillColor(BRAND.black)
      .font('Helvetica')
      .fontSize(7.8)
      .text(row[1], PAGE.left + 190, y + 7, { width: 280, lineBreak: false });
  });

  cursor.y += rows.length * 21 + 26;

  doc.roundedRect(PAGE.left, cursor.y, PAGE.contentWidth, 82, 8).fill(BRAND.panel);
  doc.rect(PAGE.left, cursor.y, 5, 82).fill(BRAND.gold);

  doc
    .fillColor(BRAND.gold)
    .font('Helvetica-Bold')
    .fontSize(8)
    .text('REVIEW AND RELIANCE NOTICE', PAGE.left + 18, cursor.y + 14);
  doc
    .fillColor(BRAND.black)
    .font('Helvetica')
    .fontSize(8.1)
    .text(
      'This artifact is generated by Wilsy OS as an enterprise source-aware control document. It is not final for signature, external circulation, filing, regulatory submission, investor diligence, litigation or commercial reliance until reviewed by the responsible business owner and, where appropriate, legal, finance, security, privacy, compliance or executive leadership.',
      PAGE.left + 18,
      cursor.y + 31,
      { width: 450, lineGap: 2.2 }
    );

  cursor.y += 106;

  return cursor;
}

/**
 * @function startEnterprisePdfBodyPage
 * @description Starts a clean body page below the enterprise chrome-safe area and returns the active cursor.
 * @param {PDFDocument} doc - PDF document.
 * @param {object} cursor - Cursor state.
 * @returns {object} Cursor positioned at the protected body top.
 * @collaboration CRM Proof Pack layout, enterprise PDF chrome, pagination safety, and proof-readable export output.
 */
function startEnterprisePdfBodyPage(doc, cursor) {
  const nextCursor = normalizeEnterprisePdfCursor(cursor, PAGE.top);
  doc.addPage();
  nextCursor.y = PAGE.top;
  return nextCursor;
}

/**
 * @function drawProofSchedule
 * @description Draws a proof and source completion appendix.
 * @param {PDFDocument} doc - PDF document.
 * @param {object} cursor - Cursor state.
 * @param {object} state - Render state.
 * @returns {void}
 * @collaboration Adds audit and source-control depth to generated artifacts.
 */
function drawProofSchedule(doc, cursor, state) {
  if (isWilsyKnowledgeBaseState(state)) {
    return getWilsyKnowledgeBaseScheduleSections(state).reduce(
      (nextCursor, section) => drawSection(doc, nextCursor, section),
      cursor
    );
  }

  cursor = normalizeEnterprisePdfCursor(cursor, PAGE.top);

  if (isCrmProofPackState(state)) {
    cursor = startEnterprisePdfBodyPage(doc, cursor);

    getCrmProofPackScheduleSections(state).forEach((section, index) => {
      if (index > 0) {
        cursor = startEnterprisePdfBodyPage(doc, cursor);
      }

      cursor = drawSection(doc, cursor, section);
    });

    return cursor;
  }

  cursor = startEnterprisePdfBodyPage(doc, cursor);

  cursor = drawSection(doc, cursor, {
    title: 'Schedule A — Source Fields Requiring Completion',
    paragraphs: [
      'Counterparty legal name, registration number, registered address, representative name, representative authority, commercial purpose, governing law deviations, signature method, approval owner and execution date must be completed or connected from source systems before final reliance.',
      'Where any field remains incomplete, Wilsy OS must preserve the placeholder visibly and retain the source posture so reviewers can distinguish draft automation from verified legal facts.',
    ],
  });

  cursor = drawSection(doc, cursor, {
    title: 'Schedule B — Forensic Proof Appendix',
    paragraphs: [
      `Trace ID: ${state.traceId}. Merkle Root: ${state.merkleRoot}. SHA3 / Seal: ${state.sha3}. Source Posture: ${state.sourcePosture}. Generated At: ${state.generatedAt}.`,
      'The proof appendix supports reconstruction, version comparison, audit evidence, dispute response, investor diligence and internal control review.',
    ],
  });

  return cursor;
}

/**
 * @function drawExecution
 * @description Draws premium execution blocks.
 * @param {PDFDocument} doc - PDF document.
 * @param {object} cursor - Cursor state.
 * @param {object} state - Render state.
 * @returns {void}
 * @collaboration Produces a boardroom-ready execution page for tenant-facing artifacts.
 */
function drawExecution(doc, cursor, state) {
  if (isWilsyKnowledgeBaseState(state)) {
    return drawSection(doc, cursor, {
      title: 'KNOWLEDGE BASE AUTHORITY AND RETENTION',
      paragraphs: [
        'This Wilsy OS knowledge-base playbook is retained for investor review, user enablement, future engineering continuity and internal product governance.',
        'It is not a counterparty execution artifact and must not display generic counterparty signature blocks.',
      ],
    });
  }

  cursor = normalizeEnterprisePdfCursor(cursor, PAGE.top);

  if (isCrmProofPackState(state)) {
    cursor = startEnterprisePdfBodyPage(doc, cursor);

    return drawSection(doc, cursor, {
      title: 'PROOF AUTHORITY AND RETENTION',
      paragraphs: [
        `Tenant authority: ${state.tenantId}`,
        `Generated by: ${state.generatedBy}`,
        `Operator email: ${state.operatorEmail}`,
        `Trace ID: ${state.traceId}`,
        `Merkle Root: ${state.merkleRoot}`,
        `SHA3 / Seal: ${state.sha3}`,
        'This CRM Proof Pack is retained as Wilsy OS proof-ledger evidence. It supports audit, investor diligence, compliance review, operational reconstruction and controlled internal reliance.',
      ],
    });
  }

  cursor = startEnterprisePdfBodyPage(doc, cursor);

  doc
    .fillColor(BRAND.black)
    .font('Helvetica-Bold')
    .fontSize(15)
    .text('EXECUTION AND AUTHORITY', PAGE.left, cursor.y);
  cursor.y = doc.y + 28;

  doc
    .fillColor(BRAND.black)
    .font('Helvetica')
    .fontSize(9)
    .text(
      'IN WITNESS WHEREOF, the parties execute this artifact through authorised representatives. Electronic signatures, wet-ink signatures and system-generated proof records may be used subject to applicable law, internal approval requirements and the Wilsy OS proof trail.',
      PAGE.left,
      cursor.y,
      { width: PAGE.contentWidth, lineGap: 3 }
    );

  cursor.y = doc.y + 42;

  const blocks = [
    ['WILSY EXECUTION', state.issuingEntity, 'DIRECTOR - WILSON KHANYEZI'],
    ['COUNTERPARTY EXECUTION', state.counterparty, 'Name / Title / Authority'],
  ];

  blocks.forEach((block) => {
    ensureSpace(doc, cursor, 118);

    doc
      .fillColor(BRAND.black)
      .font('Helvetica-Bold')
      .fontSize(10)
      .text(block[0], PAGE.left, cursor.y);
    cursor.y += 24;
    doc
      .fillColor(BRAND.black)
      .font('Helvetica')
      .fontSize(8.7)
      .text(`Entity: ${block[1]}`, PAGE.left + 18, cursor.y);
    cursor.y += 38;
    doc
      .moveTo(PAGE.left + 18, cursor.y)
      .lineTo(PAGE.left + 255, cursor.y)
      .strokeColor(BRAND.black)
      .lineWidth(0.7)
      .stroke();
    cursor.y += 7;
    doc
      .fillColor(BRAND.black)
      .font('Helvetica-Bold')
      .fontSize(8.1)
      .text(block[2], PAGE.left + 18, cursor.y);
    cursor.y += 16;
    doc
      .fillColor(BRAND.black)
      .font('Helvetica')
      .fontSize(8)
      .text(`Date: ${state.effectiveDate}`, PAGE.left + 18, cursor.y);
    cursor.y += 34;
  });
}

/**
 * @function applyChrome
 * @description Applies headers and footers after final page count is known.
 * @param {PDFDocument} doc - PDF document.
 * @param {object} state - Render state.
 * @returns {void}
 * @collaboration Guarantees accurate page count and consistent enterprise document chrome.
 */
function applyChrome(doc, state) {
  const range = doc.bufferedPageRange();

  for (let pageIndex = range.start; pageIndex < range.start + range.count; pageIndex += 1) {
    doc.switchToPage(pageIndex);
    drawHeader(doc, state, pageIndex - range.start + 1, range.count);
    drawFooter(doc, state);
  }
}

/**
 * @function normalizeEnterprisePdfCursor
 * @description Guarantees the enterprise PDF renderer always has a mutable cursor before draw functions read cursor.y.
 * @param {object} cursor - Cursor returned by chrome/layout setup.
 * @param {number} fallbackY - Safe vertical position below the document chrome.
 * @returns {object} Mutable cursor with a numeric y value.
 * @collaboration Enterprise PDF renderer, CRM Proof Pack PDF adapter, PDFKit layout safety, and browser-complete artifact delivery.
 */
function normalizeEnterprisePdfCursor(cursor = {}, fallbackY = PAGE.top) {
  const resolvedCursor = cursor && typeof cursor === 'object' ? cursor : {};
  const numericY = Number(resolvedCursor.y);
  resolvedCursor.y = Number.isFinite(numericY) ? numericY : fallbackY;

  return resolvedCursor;
}

/**
 * @function streamEnterpriseArtifactPdf
 * @description Streams a Wilsy OS enterprise PDF artifact with stable branding, pagination and deeper content.
 * @param {object} args - Render arguments.
 * @returns {Promise<void>} Streams the PDF response.
 * @collaboration Replaces shallow draft documents with tenant-facing enterprise artifact output.
 */
export async function streamEnterpriseArtifactPdf({ res, identity, proof }) {
  const state = hydrateWilsyKnowledgeBaseState(
    hydrateCrmProofPackState(buildState(identity, proof), identity, proof),
    identity,
    proof
  );
  const fileName = `WILSY-OS-${safeFileName(state.title)}-${state.tenantId}-${Date.now()}.pdf`;

  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename="${fileName}"`);
  res.setHeader('X-Wilsy-Trace-ID', state.traceId);
  res.setHeader('X-Wilsy-Merkle-Root', state.merkleRoot);
  res.setHeader('X-Wilsy-Artifact-Type', state.type);
  res.setHeader('X-Wilsy-Tenant-ID', state.tenantId);

  const doc = new PDFDocument({
    size: 'A4',
    bufferPages: true,
    margins: { top: 0, bottom: 0, left: 0, right: 0 },
    info: {
      Title: state.title,
      Author: 'Wilsy OS',
      Subject: `Wilsy OS Enterprise Artifact - ${state.type}`,
      Keywords: `Wilsy OS, ${state.type}, ${state.tenantId}, ${state.traceId}`,
    },
  });

  const pdfChunks = [];
  const pdfBufferReady = new Promise((resolve, reject) => {
    doc.on('data', (chunk) => {
      if (chunk) pdfChunks.push(Buffer.from(chunk));
    });

    doc.on('end', () => {
      resolve(Buffer.concat(pdfChunks));
    });

    doc.on('error', reject);
  });

  let cursor = normalizeEnterprisePdfCursor({ y: PAGE.top }, PAGE.top);

  cursor = drawDocumentControl(doc, cursor, state);
  buildSections(state).forEach((section) => {
    cursor = drawSection(doc, cursor, section);
  });
  cursor = drawProofSchedule(doc, cursor, state);
  cursor = drawExecution(doc, cursor, state);
  applyChrome(doc, state);

  doc.end();

  const pdfBuffer = await pdfBufferReady;

  if (!pdfBuffer || pdfBuffer.length < 128) {
    throw new Error('Enterprise PDF renderer produced an incomplete PDF buffer.');
  }

  res.setHeader('Content-Length', String(pdfBuffer.length));
  res.end(pdfBuffer);
}

export default streamEnterpriseArtifactPdf;

// P60K5Q10FG106O_ENTERPRISE_RENDERER_CRM_PROOF_STORY\n\n// P60K5Q10FG106S_BUFFER_ENTERPRISE_PDF_FINALIZATION\n

// P60K5Q10FG106T_ENTERPRISE_PDF_CURSOR_GUARD

// P60K5Q10FG106T3_CURSOR_ORDER_RESCUE

// P60K5Q10FG106U_ENTERPRISE_PDF_ALL_CURSOR_READ_GUARDS

// P60K5Q10FG106X_CRM_PROOF_PACK_PDF_LAYOUT_FLOW

// P60K5Q10FG106Y_PDF_CURSOR_MUTATION_FLOW

// P60K5Q10FG106Z_GENERATED_BY_HUMAN_CONTROL_NAME
