import os, uuid
from typing import Any, Optional
from datetime import date, datetime, timezone, timedelta
from pymongo import MongoClient
from tools.eos.saas.domain.vendor import VendorIdentity
from tools.eos.saas.domain.vendor_bill import VendorBill
from tools.eos.saas.domain.financial_approval_policy_evaluation import *
from tools.eos.saas.domain.financial_approval_decision import FinancialApprovalDecision, FinancialApprovalDecisionType, FinancialApprovalSubjectType as DST
from tools.eos.saas.domain.financial_approval_actor_authorization import FinancialApprovalActorAuthorization
from tools.eos.saas.billing.vendor_registry import VendorRegistry
from tools.eos.saas.billing.vendor_bill_registry import VendorBillRegistry
from tools.eos.saas.billing.financial_approval_policy_evaluation_registry import FinancialApprovalPolicyEvaluationRegistry, _compute_vendor_bill_policy_snapshot_fingerprint
from tools.eos.saas.billing.financial_approval_decision_registry import FinancialApprovalDecisionRegistry
from tools.eos.saas.billing.financial_approval_actor_authorization_registry import FinancialApprovalActorAuthorizationRegistry
from tools.eos.saas.billing.financial_approval_aggregator import FinancialApprovalAggregator
from tools.eos.saas.domain.financial_approval_effective_result import FinancialApprovalEffectiveState

def fixture(required=1,rejection_rule=FinancialApprovalRejectionRule.ANY_VALID_REJECTION_BLOCKS,rejections_required=None):
 c=MongoClient(os.environ['TEST_VENDOR_MONGO_URI']); db=c['aggregator_'+uuid.uuid4().hex]; v,b,p,d,a=[db[x] for x in ('vendors','vendor_bills','financial_approval_policy_evaluations','financial_approval_decisions','financial_approval_actor_authorizations')]; VendorRegistry.ensure_indexes(v); VendorBillRegistry.ensure_indexes(b); FinancialApprovalPolicyEvaluationRegistry.ensure_indexes(p); FinancialApprovalDecisionRegistry.ensure_indexes(d); FinancialApprovalActorAuthorizationRegistry.ensure_indexes(a); vendor=VendorRegistry.create(VendorIdentity(tenant_id='t',legal_name='V'),v); bill=VendorBill(tenant_id='t',vendor_id=vendor.vendor_id,payable_id='p',gross_amount_minor=100,currency='ZAR',issue_date=date(2026,1,1),due_date=date(2026,2,1),received_at=datetime(2026,1,1,tzinfo=timezone.utc),approval_policy_reference='P'); VendorBillRegistry.create(bill,b); opened=VendorBillRegistry.open_bill('t','p',1,'open',b).vendor_bill; req=FinancialApprovalRequirement('r','CFO',max(required,1)); ev=FinancialApprovalPolicyEvaluation(tenant_id='t',evaluation_id='e',subject_type=FinancialApprovalPolicySubjectType.VENDOR_BILL,subject_id='p',subject_revision=2,approval_policy_reference='P',approval_policy_version='1',approval_required=required>0,approval_requirements=(req,) if required else (),rejection_rule=rejection_rule,rejections_required=rejections_required,subject_snapshot_fingerprint=_compute_vendor_bill_policy_snapshot_fingerprint(opened),evaluator_reference='r',evaluated_at=datetime(2026,1,1,tzinfo=timezone.utc),created_at=datetime(2026,1,1,tzinfo=timezone.utc)); FinancialApprovalPolicyEvaluationRegistry.create(ev,'ek',p); return c,db,p,d,a,ev,opened

def add_evidence(d,a,ev,opened,actor,decision_id,outcome=FinancialApprovalDecisionType.APPROVED,when=datetime(2026,1,1,tzinfo=timezone.utc),requirement_id='r',capacity='CFO',policy_reference='P',policy_version: Optional[str]='1',subject_revision=2,authorized_at=datetime(2026,1,1,tzinfo=timezone.utc),valid_until=None,auth_actor=None,auth_capacity=None,authorization_id=None):
 decision=FinancialApprovalDecision(tenant_id='t',decision_id=decision_id,subject_type=DST.VENDOR_BILL,subject_id='p',decision=outcome,actor_id=actor,actor_capacity=capacity,reason='r',approval_policy_reference=policy_reference,approval_policy_version=policy_version,subject_revision=subject_revision,decided_at=when,created_at=when); auth=FinancialApprovalActorAuthorization(tenant_id='t',authorization_id=authorization_id or 'a-'+decision_id,subject_type=FinancialApprovalPolicySubjectType.VENDOR_BILL,subject_id='p',subject_revision=subject_revision,evaluation_id='e',approval_policy_reference='P',approval_policy_version='1',requirement_id=requirement_id,actor_id=auth_actor or actor,actor_capacity=auth_capacity or capacity,authorization_source_reference='s',authorization_basis_reference='b',authorized_at=authorized_at,valid_until=valid_until,authorization_evidence_fingerprint='a'*128,created_at=when); FinancialApprovalDecisionRegistry.create(decision,'k-'+decision_id,d); FinancialApprovalActorAuthorizationRegistry.create(auth,'ak-'+decision_id,a)

def multi_lane_fixture_legacy():
 # Persist the draft before applying the CAS transition.
 c=MongoClient(os.environ['TEST_VENDOR_MONGO_URI']); db=c['aggregator_'+uuid.uuid4().hex]; v,b,p,d,a=[db[x] for x in ('vendors','vendor_bills','financial_approval_policy_evaluations','financial_approval_decisions','financial_approval_actor_authorizations')]; VendorRegistry.ensure_indexes(v); VendorBillRegistry.ensure_indexes(b); FinancialApprovalPolicyEvaluationRegistry.ensure_indexes(p); FinancialApprovalDecisionRegistry.ensure_indexes(d); FinancialApprovalActorAuthorizationRegistry.ensure_indexes(a); vendor=VendorRegistry.create(VendorIdentity(tenant_id='t',legal_name='V'),v); bill=VendorBill(tenant_id='t',vendor_id=vendor.vendor_id,payable_id='p',gross_amount_minor=100,currency='ZAR',issue_date=date(2026,1,1),due_date=date(2026,2,1),received_at=datetime(2026,1,1,tzinfo=timezone.utc),approval_policy_reference='P'); opened=VendorBillRegistry.open_bill('t','p',1,'open',b).vendor_bill; reqs=(FinancialApprovalRequirement('r1','CFO',1),FinancialApprovalRequirement('r2','CFO',1)); ev=FinancialApprovalPolicyEvaluation(tenant_id='t',evaluation_id='e',subject_type=FinancialApprovalPolicySubjectType.VENDOR_BILL,subject_id='p',subject_revision=2,approval_policy_reference='P',approval_policy_version='1',approval_required=True,approval_requirements=reqs,rejection_rule=FinancialApprovalRejectionRule.ANY_VALID_REJECTION_BLOCKS,rejections_required=None,subject_snapshot_fingerprint=_compute_vendor_bill_policy_snapshot_fingerprint(opened),evaluator_reference='r',evaluated_at=datetime(2026,1,1,tzinfo=timezone.utc),created_at=datetime(2026,1,1,tzinfo=timezone.utc)); FinancialApprovalPolicyEvaluationRegistry.create(ev,'ek',p); return c,db,p,d,a,ev,opened

def test_aggregator_states_and_distinct_quorum_real_mongo():
 c,db,p,d,a,ev,opened=fixture(0); result=FinancialApprovalAggregator(database=db).aggregate('t','e','r0',datetime(2026,1,2,tzinfo=timezone.utc),datetime(2026,1,2,tzinfo=timezone.utc)); assert result.effective_state is FinancialApprovalEffectiveState.NOT_REQUIRED; c.drop_database(db.name); c.close()
 c,db,p,d,a,ev,opened=fixture(2); add_evidence(d,a,ev,opened,'A','d1'); result=FinancialApprovalAggregator(database=db).aggregate('t','e','r1',datetime(2026,1,2,tzinfo=timezone.utc),datetime(2026,1,2,tzinfo=timezone.utc)); assert result.effective_state is FinancialApprovalEffectiveState.PENDING and result.requirement_results[0].approvals_counted==1; add_evidence(d,a,ev,opened,'B','d2'); result=FinancialApprovalAggregator(database=db).aggregate('t','e','r2',datetime(2026,1,2,tzinfo=timezone.utc),datetime(2026,1,2,tzinfo=timezone.utc)); assert result.effective_state is FinancialApprovalEffectiveState.APPROVED and result.source_evidence_fingerprint != ''
 c.drop_database(db.name); c.close()

def test_aggregator_rejection_precedence_and_fingerprint_real_mongo():
 c,db,p,d,a,ev,opened=fixture(1); add_evidence(d,a,ev,opened,'A','d1'); add_evidence(d,a,ev,opened,'B','reject',FinancialApprovalDecisionType.REJECTED); first=FinancialApprovalAggregator(database=db).aggregate('t','e','r1',datetime(2026,1,2,tzinfo=timezone.utc),datetime(2026,1,2,tzinfo=timezone.utc)); second=FinancialApprovalAggregator(database=db).aggregate('t','e','r2',datetime(2026,1,2,tzinfo=timezone.utc),datetime(2026,1,2,tzinfo=timezone.utc)); assert first.effective_state is FinancialApprovalEffectiveState.REJECTED and first.source_evidence_fingerprint==second.source_evidence_fingerprint; c.drop_database(db.name); c.close()

def test_duplicate_actor_approvals_do_not_inflate_quorum_real_mongo():
 c,db,p,d,a,ev,opened=fixture(2)
 for i in range(3): add_evidence(d,a,ev,opened,'A',f'a{i}',when=datetime(2026,1,1+i,tzinfo=timezone.utc))
 result=FinancialApprovalAggregator(database=db).aggregate('t','e','dup1',datetime(2026,1,5,tzinfo=timezone.utc),datetime(2026,1,5,tzinfo=timezone.utc)); assert result.requirement_results[0].approvals_counted==1 and result.effective_state is FinancialApprovalEffectiveState.PENDING and len(result.requirement_results[0].counted_actor_ids)==1
 add_evidence(d,a,ev,opened,'B','b1',when=datetime(2026,1,4,tzinfo=timezone.utc)); result=FinancialApprovalAggregator(database=db).aggregate('t','e','dup2',datetime(2026,1,5,tzinfo=timezone.utc),datetime(2026,1,5,tzinfo=timezone.utc)); assert result.requirement_results[0].approvals_counted==2 and result.effective_state is FinancialApprovalEffectiveState.APPROVED; c.drop_database(db.name); c.close()

def test_approve_then_reject_latest_decision_wins_real_mongo():
 c,db,p,d,a,ev,opened=fixture(1); add_evidence(d,a,ev,opened,'A','approved',when=datetime(2026,1,1,tzinfo=timezone.utc)); add_evidence(d,a,ev,opened,'A','rejected',FinancialApprovalDecisionType.REJECTED,datetime(2026,1,2,tzinfo=timezone.utc)); result=FinancialApprovalAggregator(database=db).aggregate('t','e','ar',datetime(2026,1,3,tzinfo=timezone.utc),datetime(2026,1,3,tzinfo=timezone.utc)); assert result.effective_state is FinancialApprovalEffectiveState.REJECTED and 'approved' in [x.decision_id for x in result.excluded_decisions]; c.drop_database(db.name); c.close()

def test_reject_then_approve_latest_decision_wins_real_mongo():
 c,db,p,d,a,ev,opened=fixture(1); add_evidence(d,a,ev,opened,'A','rejected',FinancialApprovalDecisionType.REJECTED,datetime(2026,1,1,tzinfo=timezone.utc)); add_evidence(d,a,ev,opened,'A','approved',when=datetime(2026,1,2,tzinfo=timezone.utc)); result=FinancialApprovalAggregator(database=db).aggregate('t','e','ra',datetime(2026,1,3,tzinfo=timezone.utc),datetime(2026,1,3,tzinfo=timezone.utc)); assert result.effective_state is FinancialApprovalEffectiveState.APPROVED and 'rejected' in [x.decision_id for x in result.excluded_decisions]; c.drop_database(db.name); c.close()

def test_decided_at_tie_breaks_by_decision_id_real_mongo():
 c,db,p,d,a,ev,opened=fixture(1); when=datetime(2026,1,1,tzinfo=timezone.utc); add_evidence(d,a,ev,opened,'A','b-decision',FinancialApprovalDecisionType.REJECTED,when); add_evidence(d,a,ev,opened,'A','a-decision',when=when); result=FinancialApprovalAggregator(database=db).aggregate('t','e','tie',datetime(2026,1,3,tzinfo=timezone.utc),datetime(2026,1,3,tzinfo=timezone.utc)); assert result.effective_state is FinancialApprovalEffectiveState.APPROVED and 'b-decision' in [x.decision_id for x in result.excluded_decisions]; c.drop_database(db.name); c.close()

def multi_lane_fixture():
 c,db,p,d,a,ev,opened=fixture(1)
 p.delete_many({})
 reqs=(FinancialApprovalRequirement('r1','CFO',1),FinancialApprovalRequirement('r2','CONTROLLER',1))
 ev=FinancialApprovalPolicyEvaluation(tenant_id='t',evaluation_id='e',subject_type=FinancialApprovalPolicySubjectType.VENDOR_BILL,subject_id='p',subject_revision=2,approval_policy_reference='P',approval_policy_version='1',approval_required=True,approval_requirements=reqs,rejection_rule=FinancialApprovalRejectionRule.ANY_VALID_REJECTION_BLOCKS,rejections_required=None,subject_snapshot_fingerprint=_compute_vendor_bill_policy_snapshot_fingerprint(opened),evaluator_reference='r',evaluated_at=datetime(2026,1,1,tzinfo=timezone.utc),created_at=datetime(2026,1,1,tzinfo=timezone.utc))
 FinancialApprovalPolicyEvaluationRegistry.create(ev,'ek',p)
 return c,db,p,d,a,ev,opened

def test_same_actor_two_lanes_requires_two_distinct_decisions_real_mongo():
 c,db,p,d,a,ev,opened=multi_lane_fixture(); add_evidence(d,a,ev,opened,'A','r1-decision',requirement_id='r1',capacity='CFO'); add_evidence(d,a,ev,opened,'A','r2-decision',requirement_id='r2',capacity='CONTROLLER'); result=FinancialApprovalAggregator(database=db).aggregate('t','e','lanes',datetime(2026,1,2,tzinfo=timezone.utc),datetime(2026,1,2,tzinfo=timezone.utc)); assert result.effective_state is FinancialApprovalEffectiveState.APPROVED and [r.approvals_counted for r in result.requirement_results]==[1,1]; c.drop_database(db.name); c.close()

def _excluded(result, decision_id, reason):
 assert decision_id not in result.counted_decision_ids
 assert any(x.decision_id == decision_id and x.reason.value == reason for x in result.excluded_decisions)

def test_policy_version_strictness_real_mongo():
 for version, reason in ((None,'POLICY_VERSION_MISSING'),('v1','POLICY_VERSION_MISMATCH')):
  c,db,p,d,a,ev,opened=fixture(1); add_evidence(d,a,ev,opened,'A','pv',policy_version=version); result=FinancialApprovalAggregator(database=db).aggregate('t','e','pv-'+str(version),datetime(2026,1,2,tzinfo=timezone.utc),datetime(2026,1,2,tzinfo=timezone.utc)); _excluded(result,'pv',reason); assert result.effective_state is FinancialApprovalEffectiveState.PENDING; c.drop_database(db.name); c.close()
 c,db,p,d,a,ev,opened=fixture(1); add_evidence(d,a,ev,opened,'A','pr',policy_reference='policy-X'); result=FinancialApprovalAggregator(database=db).aggregate('t','e','pr',datetime(2026,1,2,tzinfo=timezone.utc),datetime(2026,1,2,tzinfo=timezone.utc)); _excluded(result,'pr','POLICY_REFERENCE_MISMATCH'); c.drop_database(db.name); c.close()

def test_authorization_time_validity_boundaries_real_mongo():
 t=datetime(2026,1,2,tzinfo=timezone.utc)
 cases=((t+timedelta(days=1),None,'AUTHORIZATION_NOT_YET_VALID'),(t-timedelta(days=1),t-timedelta(seconds=1),'AUTHORIZATION_EXPIRED'))
 for authorized,until,reason in cases:
  c,db,p,d,a,ev,opened=fixture(1); add_evidence(d,a,ev,opened,'A','time',when=t,authorized_at=authorized,valid_until=until); result=FinancialApprovalAggregator(database=db).aggregate('t','e','time'+reason, t,t); _excluded(result,'time',reason); c.drop_database(db.name); c.close()
 for authorized,until in ((t,t),(t-timedelta(days=1),t),(t-timedelta(days=1),None)):
  c,db,p,d,a,ev,opened=fixture(1); add_evidence(d,a,ev,opened,'A','valid',when=t,authorized_at=authorized,valid_until=until); result=FinancialApprovalAggregator(database=db).aggregate('t','e','valid'+str(until), t,t); assert result.effective_state is FinancialApprovalEffectiveState.APPROVED and result.requirement_results[0].approvals_counted == 1; c.drop_database(db.name); c.close()

def test_authorization_identity_and_capacity_matrix_real_mongo():
 c,db,p,d,a,ev,opened=fixture(1); add_evidence(d,a,ev,opened,'A','cap',capacity='PARTNER',auth_capacity='CFO'); result=FinancialApprovalAggregator(database=db).aggregate('t','e','cap',datetime(2026,1,2,tzinfo=timezone.utc),datetime(2026,1,2,tzinfo=timezone.utc)); _excluded(result,'cap','ACTOR_CAPACITY_MISMATCH'); c.drop_database(db.name); c.close()
 c,db,p,d,a,ev,opened=fixture(1); add_evidence(d,a,ev,opened,'B','unauth',auth_actor='C'); result=FinancialApprovalAggregator(database=db).aggregate('t','e','unauth',datetime(2026,1,2,tzinfo=timezone.utc),datetime(2026,1,2,tzinfo=timezone.utc)); _excluded(result,'unauth','UNAUTHORIZED_ACTOR'); c.drop_database(db.name); c.close()
 c,db,p,d,a,ev,opened=fixture(1); add_evidence(d,a,ev,opened,'A','wrong-auth',auth_actor='B'); result=FinancialApprovalAggregator(database=db).aggregate('t','e','wrong-auth',datetime(2026,1,2,tzinfo=timezone.utc),datetime(2026,1,2,tzinfo=timezone.utc)); _excluded(result,'wrong-auth','UNAUTHORIZED_ACTOR'); c.drop_database(db.name); c.close()

def legacy_multiple_authorizations_are_deterministic_and_do_not_inflate_real_mongo():
 c,db,p,d,a,ev,opened=fixture(1); when=datetime(2026,1,1,tzinfo=timezone.utc); add_evidence(d,a,ev,opened,'A','multi',authorized_at=when,authorization_id='b-auth'); auth=FinancialApprovalActorAuthorization(tenant_id='t',authorization_id='a-auth',subject_type=FinancialApprovalPolicySubjectType.VENDOR_BILL,subject_id='p',subject_revision=2,evaluation_id='e',approval_policy_reference='P',approval_policy_version='1',requirement_id='r',actor_id='A',actor_capacity='CFO',authorization_source_reference='s',authorization_basis_reference='b',authorized_at=when-timedelta(days=1),authorization_evidence_fingerprint='b'*128,created_at=when); FinancialApprovalActorAuthorizationRegistry.create(auth,'ak-a-auth',a); result=FinancialApprovalAggregator(database=db).aggregate('t','e','multi',datetime(2026,1,2,tzinfo=timezone.utc),datetime(2026,1,2,tzinfo=timezone.utc)); assert result.requirement_results[0].approvals_counted == 1 and result.counted_authorization_ids == ('a-auth',); c.drop_database(db.name); c.close()

def test_lane_ambiguity_order_independence_and_wrong_revision_real_mongo():
 for reverse in (False,True):
  c,db,p,d,a,ev,opened=fixture(1); p.delete_many({}); reqs=(FinancialApprovalRequirement('r1','CFO',1),FinancialApprovalRequirement('r2','CFO',1)); ev=FinancialApprovalPolicyEvaluation(tenant_id='t',evaluation_id='e',subject_type=FinancialApprovalPolicySubjectType.VENDOR_BILL,subject_id='p',subject_revision=2,approval_policy_reference='P',approval_policy_version='1',approval_required=True,approval_requirements=reqs,rejection_rule=FinancialApprovalRejectionRule.ANY_VALID_REJECTION_BLOCKS,rejections_required=None,subject_snapshot_fingerprint=_compute_vendor_bill_policy_snapshot_fingerprint(opened),evaluator_reference='r',evaluated_at=datetime(2026,1,1,tzinfo=timezone.utc),created_at=datetime(2026,1,1,tzinfo=timezone.utc)); FinancialApprovalPolicyEvaluationRegistry.create(ev,'ek',p); ids=('r2','r1') if reverse else ('r1','r2'); add_evidence(d,a,ev,opened,'A','amb',requirement_id=ids[0]); add_evidence(d,a,ev,opened,'A','amb2',requirement_id=ids[1]); result=FinancialApprovalAggregator(database=db).aggregate('t','e','amb'+str(reverse),datetime(2026,1,2,tzinfo=timezone.utc),datetime(2026,1,2,tzinfo=timezone.utc)); assert result.effective_state is FinancialApprovalEffectiveState.PENDING and all(r.approvals_counted == 0 for r in result.requirement_results) and any(x.reason.value == 'AMBIGUOUS_REQUIREMENT_MAPPING' for x in result.excluded_decisions); c.drop_database(db.name); c.close()
 c,db,p,d,a,ev,opened=fixture(1); add_evidence(d,a,ev,opened,'A','wrong-rev'); raw=d.find_one({'decision_id':'wrong-rev'}); assert raw is not None; raw['subject_revision']=3; d.replace_one({'decision_id':'wrong-rev'},raw); result=FinancialApprovalAggregator(database=db).aggregate('t','e','wrong-rev',datetime(2026,1,2,tzinfo=timezone.utc),datetime(2026,1,2,tzinfo=timezone.utc)); _excluded(result,'wrong-rev','WRONG_SUBJECT_REVISION'); c.drop_database(db.name); c.close()

def test_multiple_authorizations_are_deterministic_and_do_not_inflate_real_mongo():
 c,db,p,d,a,ev,opened=fixture(1); when=datetime(2026,1,1,tzinfo=timezone.utc); add_evidence(d,a,ev,opened,'A','multi',when=when+timedelta(days=2),authorized_at=when,authorization_id='b-auth'); auth=FinancialApprovalActorAuthorization(tenant_id='t',authorization_id='a-auth',subject_type=FinancialApprovalPolicySubjectType.VENDOR_BILL,subject_id='p',subject_revision=2,evaluation_id='e',approval_policy_reference='P',approval_policy_version='1',requirement_id='r',actor_id='A',actor_capacity='CFO',authorization_source_reference='s',authorization_basis_reference='b',authorized_at=when+timedelta(days=1),authorization_evidence_fingerprint='b'*128,created_at=when); FinancialApprovalActorAuthorizationRegistry.create(auth,'ak-a-auth',a); result=FinancialApprovalAggregator(database=db).aggregate('t','e','multi',datetime(2026,1,4,tzinfo=timezone.utc),datetime(2026,1,4,tzinfo=timezone.utc)); assert result.requirement_results[0].approvals_counted == 1 and result.counted_authorization_ids == ('a-auth',); c.drop_database(db.name); c.close()

def test_rejection_quorum_and_precedence_real_mongo():
 c,db,p,d,a,ev,opened=fixture(1); add_evidence(d,a,ev,opened,'A','reject',FinancialApprovalDecisionType.REJECTED); result=FinancialApprovalAggregator(database=db).aggregate('t','e','single',datetime(2026,1,2,tzinfo=timezone.utc),datetime(2026,1,2,tzinfo=timezone.utc)); assert result.effective_state is FinancialApprovalEffectiveState.REJECTED and result.rejection_actor_ids == ('A',); c.drop_database(db.name); c.close()
 c,db,p,d,a,ev,opened=fixture(1,rejection_rule=FinancialApprovalRejectionRule.REJECTION_QUORUM,rejections_required=2); add_evidence(d,a,ev,opened,'A','approve'); add_evidence(d,a,ev,opened,'B','reject',FinancialApprovalDecisionType.REJECTED); result=FinancialApprovalAggregator(database=db).aggregate('t','e','below',datetime(2026,1,2,tzinfo=timezone.utc),datetime(2026,1,2,tzinfo=timezone.utc)); assert result.effective_state is FinancialApprovalEffectiveState.APPROVED and result.rejections_counted == 1; add_evidence(d,a,ev,opened,'C','reject2',FinancialApprovalDecisionType.REJECTED); result=FinancialApprovalAggregator(database=db).aggregate('t','e','sat',datetime(2026,1,2,tzinfo=timezone.utc),datetime(2026,1,2,tzinfo=timezone.utc)); assert result.effective_state is FinancialApprovalEffectiveState.REJECTED and result.rejection_actor_ids == ('B','C'); c.drop_database(db.name); c.close()

def test_duplicate_and_multilane_rejectors_count_once_real_mongo():
 c,db,p,d,a,ev,opened=fixture(1,rejection_rule=FinancialApprovalRejectionRule.REJECTION_QUORUM,rejections_required=2)
 for i in range(3): add_evidence(d,a,ev,opened,'A',f'ar{i}',FinancialApprovalDecisionType.REJECTED,when=datetime(2026,1,1+i,tzinfo=timezone.utc))
 result=FinancialApprovalAggregator(database=db).aggregate('t','e','dup-rej',datetime(2026,1,5,tzinfo=timezone.utc),datetime(2026,1,5,tzinfo=timezone.utc)); assert result.rejections_counted == 1 and result.effective_state is FinancialApprovalEffectiveState.PENDING; add_evidence(d,a,ev,opened,'B','br',FinancialApprovalDecisionType.REJECTED); result=FinancialApprovalAggregator(database=db).aggregate('t','e','dup-rej2',datetime(2026,1,5,tzinfo=timezone.utc),datetime(2026,1,5,tzinfo=timezone.utc)); assert result.rejections_counted == 2 and result.effective_state is FinancialApprovalEffectiveState.REJECTED; c.drop_database(db.name); c.close()
 c,db,p,d,a,ev,opened=multi_lane_fixture(); p.delete_many({}); reqs=(FinancialApprovalRequirement('r1','CFO',1),FinancialApprovalRequirement('r2','CONTROLLER',1)); ev=FinancialApprovalPolicyEvaluation(tenant_id='t',evaluation_id='e',subject_type=FinancialApprovalPolicySubjectType.VENDOR_BILL,subject_id='p',subject_revision=2,approval_policy_reference='P',approval_policy_version='1',approval_required=True,approval_requirements=reqs,rejection_rule=FinancialApprovalRejectionRule.REJECTION_QUORUM,rejections_required=2,subject_snapshot_fingerprint=_compute_vendor_bill_policy_snapshot_fingerprint(opened),evaluator_reference='r',evaluated_at=datetime(2026,1,1,tzinfo=timezone.utc),created_at=datetime(2026,1,1,tzinfo=timezone.utc)); FinancialApprovalPolicyEvaluationRegistry.create(ev,'ek',p); add_evidence(d,a,ev,opened,'A','lane1',FinancialApprovalDecisionType.REJECTED,requirement_id='r1',capacity='CFO'); add_evidence(d,a,ev,opened,'A','lane2',FinancialApprovalDecisionType.REJECTED,requirement_id='r2',capacity='CONTROLLER'); result=FinancialApprovalAggregator(database=db).aggregate('t','e','lanes-rej',datetime(2026,1,2,tzinfo=timezone.utc),datetime(2026,1,2,tzinfo=timezone.utc)); assert result.rejections_counted == 1; c.drop_database(db.name); c.close()

def test_superseded_rejections_and_invalid_rejections_do_not_block_real_mongo():
 c,db,p,d,a,ev,opened=fixture(1); add_evidence(d,a,ev,opened,'A','old-rej',FinancialApprovalDecisionType.REJECTED,when=datetime(2026,1,1,tzinfo=timezone.utc)); add_evidence(d,a,ev,opened,'A','new-app',when=datetime(2026,1,2,tzinfo=timezone.utc)); result=FinancialApprovalAggregator(database=db).aggregate('t','e','sup',datetime(2026,1,3,tzinfo=timezone.utc),datetime(2026,1,3,tzinfo=timezone.utc)); assert result.effective_state is FinancialApprovalEffectiveState.APPROVED and 'old-rej' not in result.rejection_decision_ids; c.drop_database(db.name); c.close()
 cases: tuple[tuple[dict[str, Any], str], ...] = (({'auth_actor':'B'},'UNAUTHORIZED_ACTOR'),({'authorized_at':datetime(2026,1,3,tzinfo=timezone.utc)},'AUTHORIZATION_NOT_YET_VALID'),({'authorized_at':datetime(2025,12,1,tzinfo=timezone.utc),'valid_until':datetime(2025,12,31,tzinfo=timezone.utc)},'AUTHORIZATION_EXPIRED'),({'policy_version':'v9'},'POLICY_VERSION_MISMATCH'),({'policy_version':None},'POLICY_VERSION_MISSING'))
 for kwargs,reason in cases:
  c,db,p,d,a,ev,opened=fixture(1); add_evidence(d,a,ev,opened,'A','bad',FinancialApprovalDecisionType.REJECTED,**kwargs); add_evidence(d,a,ev,opened,'B','good'); result=FinancialApprovalAggregator(database=db).aggregate('t','e','bad'+reason,datetime(2026,1,4,tzinfo=timezone.utc),datetime(2026,1,4,tzinfo=timezone.utc)); _excluded(result,'bad',reason); assert result.effective_state is FinancialApprovalEffectiveState.APPROVED; c.drop_database(db.name); c.close()

def test_rejection_evidence_order_is_deterministic_real_mongo():
 c,db,p,d,a,ev,opened=fixture(1,rejection_rule=FinancialApprovalRejectionRule.REJECTION_QUORUM,rejections_required=2); add_evidence(d,a,ev,opened,'B','z-reject',FinancialApprovalDecisionType.REJECTED); add_evidence(d,a,ev,opened,'A','a-reject',FinancialApprovalDecisionType.REJECTED); first=FinancialApprovalAggregator(database=db).aggregate('t','e','order-1',datetime(2026,1,2,tzinfo=timezone.utc),datetime(2026,1,2,tzinfo=timezone.utc)); second=FinancialApprovalAggregator(database=db).aggregate('t','e','order-2',datetime(2026,1,2,tzinfo=timezone.utc),datetime(2026,1,2,tzinfo=timezone.utc)); assert first.effective_state is FinancialApprovalEffectiveState.REJECTED and first.rejection_actor_ids == ('A','B') and first.rejection_decision_ids == ('a-reject','z-reject') and first.rejection_actor_ids == second.rejection_actor_ids and first.rejection_decision_ids == second.rejection_decision_ids; c.drop_database(db.name); c.close()

def test_source_fingerprint_is_metadata_independent_and_evidence_sensitive_real_mongo():
 c,db,p,d,a,ev,opened=fixture(1); add_evidence(d,a,ev,opened,'A','fp'); first=FinancialApprovalAggregator(database=db).aggregate('t','e','result-a',datetime(2026,1,2,tzinfo=timezone.utc),datetime(2026,1,2,tzinfo=timezone.utc)); second=FinancialApprovalAggregator(database=db).aggregate('t','e','result-b',datetime(2026,2,2,tzinfo=timezone.utc),datetime(2026,2,2,tzinfo=timezone.utc)); assert isinstance(first.source_evidence_fingerprint,str) and len(first.source_evidence_fingerprint)==128 and first.source_evidence_fingerprint == second.source_evidence_fingerprint; add_evidence(d,a,ev,opened,'B','fp2'); third=FinancialApprovalAggregator(database=db).aggregate('t','e','result-c',datetime(2026,2,2,tzinfo=timezone.utc),datetime(2026,2,2,tzinfo=timezone.utc)); assert third.source_evidence_fingerprint != first.source_evidence_fingerprint; c.drop_database(db.name); c.close()
