/* eslint-disable */
/**
 * ╔════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╗
 * ║ WILSY OS - SOVEREIGN STRIKE CLIENT [V35.0.0-OMEGA]                                                                                     ║
 * ║ [RECTIFIED: GROK ALIGNMENT | UNIVERSAL RSA-SHA256 SIGNATURE | BILLION DOLLAR SPEC]                                                     ║
 * ╠════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╣
 * ║ PRODUCTION READY | EPITOME: NO CHILD'S PLACE | BIBLICAL WORTH BILLIONS                                                                 ║
 * ║ ABSOLUTE PATH: /Users/wilsonkhanyezi/legal-doc-system/server/verify_strike.js                                                          ║
 * ╠════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╣
 * ║ 👥 COLLABORATION COMMENTS:                                                                                                             ║
 * ║ • Wilson Khanyezi (CEO/Lead Architect) - Instituted permanent structural fix shifting to universal RSA-SHA256 verification. [2026-05-06] ║
 * ║ • AI Engineering (Gemini) - Aligned strike client payload and signature algorithm to precisely match Sovereign Gateway. [2026-05-06]   ║
 * ╚════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╝
 */

import fetch from 'node-fetch';
import crypto from 'crypto';
import fs from 'fs';
import chalk from 'chalk';
import readline from 'readline';

const IDENTITY = 'wilsonkhanyezi@gmail.com';
const GATEWAY_URL = 'http://localhost:5050/api/auth/verify-3fa';

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

console.log(chalk.magenta(`\n🚀 [STRIKE-INIT] Targeting Sovereign Gateway: ${GATEWAY_URL}`));

rl.question(chalk.yellow('\n🔐 ENTER 6-DIGIT SOVEREIGN OTP: '), async (inputOtp) => {
  rl.close();
  const CURRENT_OTP = inputOtp.trim();

  if (!CURRENT_OTP) {
    console.error(chalk.red('\n❌ [STRIKE-ABORTED] Missing OTP. Execution terminated.\n'));
    process.exit(1);
  }

  await performGatewayStrike(CURRENT_OTP);
});

async function performGatewayStrike(otpCode) {
  let biometricToken = '';

  try {
    console.log(chalk.cyan('\n🧬 Forging Sovereign Biometric Signature...'));

    // Read the private key generated by the forge script
    const privateKey = fs.readFileSync('private.pem', 'utf8');

    // 🚨 GROK FIX ALIGNMENT: Shifted to RSA-SHA256 to bypass OpenSSL PSS crash
    // Deterministic payload matches the controller exactly: 'wilsy-auth-challenge'
    const signature = crypto.sign(
      'RSA-SHA256',
      Buffer.from('wilsy-auth-challenge'),
      {
        key: privateKey,
        padding: crypto.constants.RSA_PKCS1_PADDING
      }
    );

    biometricToken = signature.toString('base64');
    console.log(chalk.green('✅ Signature Manifested. Initiating payload transfer...'));

  } catch (keyErr) {
    console.error(chalk.red(`\n❌ [KEY-FRACTURE] Failed to read private.pem or sign payload: ${keyErr.message}`));
    process.exit(1);
  }

  const payload = {
    email: IDENTITY,
    otp: otpCode,
    biometricToken: biometricToken
  };

  try {
    const response = await fetch(GATEWAY_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(payload)
    });

    const data = await response.json();

    if (data.success) {
      console.log(chalk.green("\n╔════════════════════════════════════════════════════════════╗"));
      console.log(chalk.green("║ ✅ SOVEREIGN GATEWAY BREACHED - JWT SHARD CAPTURED         ║"));
      console.log(chalk.green("╠════════════════════════════════════════════════════════════╣"));
      console.log(chalk.green(`║ TOKEN: ${data.token.substring(0, 50)}... ║`));
      console.log(chalk.green("╚════════════════════════════════════════════════════════════╝\n"));
      console.log(chalk.cyan("Forensic User Data:"), data.user);
    } else {
      console.error(chalk.red(`\n❌ [STRIKE-FAILED] Gateway Repelled Identity: ${data.message}`));
    }
  } catch (err) {
    console.error(chalk.red(`\n❌ [STRIKE-FRACTURE] Connection Lost: ${err.message}`));
  }
}
