apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wilsy-os
resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - storage.yaml
  - serviceaccount.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - pdb.yaml
  - ingress.yaml
  - network-policy.yaml
commonLabels:
  environment: production
  managed-by: kustomize
images:
  - name: ghcr.io/wilsy-os/predictive-engine
    newTag: latest
patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: wilsy-os-predictive
    spec:
      template:
        spec:
          containers:
          - name: predictive-engine
            env:
            - name: LOG_LEVEL
              value: debug
