// server/models/clientModel.js

const mongoose = require('mongoose');

const clientSchema = new mongoose.Schema(
    {
        // --- Client Identity ---
        firmName: {
            type: String,
            required: [true, 'A client firm name is required.'],
            trim: true,
            unique: true,
        },
        // A unique account number generated by your system for billing and reference.
        accountNumber: {
            type: String,
            required: [true, 'An account number is required.'],
            unique: true,
            uppercase: true,
            trim: true,
        },

        // --- Contact Information ---
        primaryContactName: {
            type: String,
            required: [true, 'A primary contact name is required.'],
            trim: true,
        },
        primaryContactEmail: {
            type: String,
            required: [true, 'A primary contact email is required.'],
            lowercase: true,
            trim: true,
            match: [
                /^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/,
                'Please provide a valid email address.',
            ],
        },
        phoneNumber: {
            type: String,
            trim: true,
        },
        physicalAddress: {
            type: String,
            trim: true,
        },

        // --- Billing Information ---
        accountType: {
            type: String,
            required: true,
            enum: ['COD', '30-Day Account', 'Contract'],
            default: '30-Day Account',
        },
        billingAddress: {
            type: String,
            trim: true,
        },
        vatNumber: {
            type: String,
            trim: true,
        },

        // --- Relationships ---
        // The internal user (e.g., account manager) responsible for this client.
        managedBy: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'User',
            required: true,
        },
    },
    {
        timestamps: true, // Automatically adds createdAt and updatedAt
    }
);

// --- Indexing for Performance ---
// Create an index on fields that will be frequently searched.
clientSchema.index({ firmName: 'text', accountNumber: 'text' });

const Client = mongoose.model('Client', clientSchema);

module.exports = Client;
