"""
===============================================================================
WILSY OS KERNEL ARCHITECTURE - ENTERPRISE ENGINEERING PLATFORM
===============================================================================
PROJECT: Wilsy OS (Billion-Dollar Sovereign Infrastructure)
SUBSYSTEM: Kernel ABI & Core Governance Framework
MILESTONE: FG178.5 - Kernel ABI Freeze
MODULE: kernel_abi.py

COLLABORATION & ARCHITECTURAL NOTICE:
Central registry exposing frozen runtime public interfaces for Wilsy OS.
Prevents unverified internal structures from leaking into public signatures.
===============================================================================
"""

import logging
from dataclasses import dataclass
from typing import Dict, Set, Type, Any, Optional

from tools.eos.abi.kernel_version import KernelVersionSpec, KERNEL_VERSION, ABI_VERSION
from tools.eos.abi.kernel_contracts import (
    BaseKernelEngineProtocol,
    ExecutionContextProtocol,
    EngineResultProtocol,
    LifecyclePhase,
    EngineExecutionStatus,
)

logger = logging.getLogger("WilsyOS.ABI.Registry")


@dataclass(frozen=True)
class KernelABISymbol:
    """Represents an officially exported, frozen ABI symbol."""
    symbol_name: str
    type_reference: Type[Any]
    abi_version: str
    description: str


class KernelABI:
    """
    Master registry and inspection framework for Wilsy OS Kernel ABI types.
    Maintains explicit boundaries for public contracts.
    """

    _frozen_symbols: Dict[str, KernelABISymbol] = {}
    _version_spec: KernelVersionSpec = KernelVersionSpec()
    _is_locked: bool = False

    @classmethod
    def register_symbol(
        cls,
        symbol_name: str,
        type_reference: Type[Any],
        description: str,
    ) -> None:
        """Register a public symbol as part of the frozen Kernel ABI."""
        if cls._is_locked:
            raise RuntimeError(f"Cannot register symbol '{symbol_name}'. Kernel ABI is locked!")
        
        symbol = KernelABISymbol(
            symbol_name=symbol_name,
            type_reference=type_reference,
            abi_version=ABI_VERSION,
            description=description,
        )
        cls._frozen_symbols[symbol_name] = symbol
        logger.debug("Registered Kernel ABI symbol: %s", symbol_name)

    @classmethod
    def lock_abi(cls) -> None:
        """Lock the ABI to prevent modifications at runtime."""
        cls._is_locked = True
        logger.info("Wilsy OS Kernel ABI [v%s] locked. Total public symbols: %d", ABI_VERSION, len(cls._frozen_symbols))

    @classmethod
    def is_locked(cls) -> bool:
        return cls._is_locked

    @classmethod
    def get_symbol(cls, symbol_name: str) -> Optional[KernelABISymbol]:
        return cls._frozen_symbols.get(symbol_name)

    @classmethod
    def get_registered_symbols(cls) -> Set[str]:
        return set(cls._frozen_symbols.keys())

    @classmethod
    def get_version_spec(cls) -> KernelVersionSpec:
        return cls._version_spec


# =============================================================================
# INITIALIZE & REGISTER OFFICIAL CANONICAL KERNEL ABI TYPES
# =============================================================================
def _initialize_canonical_abi() -> None:
    KernelABI.register_symbol("BaseKernelEngineProtocol", BaseKernelEngineProtocol, "Mandatory 5-stage lifecycle protocol for engines")
    KernelABI.register_symbol("ExecutionContextProtocol", ExecutionContextProtocol, "Immutable runtime context passed to engines")
    KernelABI.register_symbol("EngineResultProtocol", EngineResultProtocol, "Standardized result container generated by engines")
    KernelABI.register_symbol("LifecyclePhase", LifecyclePhase, "Lifecycle phase enumeration")
    KernelABI.register_symbol("EngineExecutionStatus", EngineExecutionStatus, "Standard execution status enumeration")
    KernelABI.lock_abi()


_initialize_canonical_abi()
