"""
===============================================================================
WILSY OS KERNEL ARCHITECTURE - ENTERPRISE ENGINEERING PLATFORM
===============================================================================
PROJECT: Wilsy OS (Billion-Dollar Sovereign Infrastructure)
SUBSYSTEM: Kernel ABI & Core Governance Framework
MILESTONE: FG178.5 - Kernel ABI Freeze
MODULE: kernel_contracts.py

COLLABORATION & ARCHITECTURAL NOTICE:
Mandatory architectural typing protocols and structural abstractions. Every
engine operating inside Wilsy OS MUST implement this strict 5-stage lifecycle:
initialize() -> validate() -> execute() -> publish() -> shutdown().
===============================================================================
"""

from abc import ABC, abstractmethod
from enum import Enum
from typing import Dict, List, Any, Optional, Protocol, runtime_checkable


class LifecyclePhase(str, Enum):
    """Standardized engine lifecycle stages enforced by the Kernel ABI."""
    UNINITIALIZED = "UNINITIALIZED"
    INITIALIZING = "INITIALIZING"
    INITIALIZED = "INITIALIZED"
    VALIDATING = "VALIDATING"
    VALIDATED = "VALIDATED"
    EXECUTING = "EXECUTING"
    EXECUTED = "EXECUTED"
    PUBLISHING = "PUBLISHING"
    PUBLISHED = "PUBLISHED"
    SHUTTING_DOWN = "SHUTTING_DOWN"
    SHUTDOWN = "SHUTDOWN"
    FAILED = "FAILED"


class EngineExecutionStatus(str, Enum):
    """Immutable execution statuses returned within EngineResult."""
    SUCCESS = "SUCCESS"
    FAILURE = "FAILURE"
    GOVERNANCE_BLOCKED = "GOVERNANCE_BLOCKED"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    SKIPPED = "SKIPPED"


class EngineCapability(str, Enum):
    """Capabilities exposed by engines for automated discovery and execution planning."""
    READ_ONLY = "READ_ONLY"
    MUTATIVE = "MUTATIVE"
    GOVERNANCE_AWARE = "GOVERNANCE_AWARE"
    REPLAY_SUPPORTED = "REPLAY_SUPPORTED"
    DISTRIBUTED_CAPABLE = "DISTRIBUTED_CAPABLE"
    TELEMETRY_ENABLED = "TELEMETRY_ENABLED"


@runtime_checkable
class ExecutionContextProtocol(Protocol):
    """Protocol for ExecutionContext expected by all engine methods."""
    execution_id: str
    session_id: str
    tenant_id: str
    metadata: Dict[str, Any]

    def get_parameter(self, key: str, default: Optional[Any] = None) -> Any:
        ...


@runtime_checkable
class EngineResultProtocol(Protocol):
    """Protocol defining the immutable result structure generated by engine execution."""
    engine_name: str
    status: EngineExecutionStatus
    execution_id: str
    outputs: Dict[str, Any]
    artifacts_created: List[Dict[str, Any]]
    events_emitted: List[Dict[str, Any]]
    execution_time_ms: float
    error_message: Optional[str]


@runtime_checkable
class BaseKernelEngineProtocol(Protocol):
    """
    Mandatory structural interface (Kernel ABI) that ALL Wilsy OS engines MUST satisfy.
    
    Execution Lifecycle:
      1. initialize(context)
      2. validate(context)
      3. execute(context) -> EngineResult
      4. publish(context)
      5. shutdown(context)
    """

    engine_name: str
    version: str
    capabilities: List[EngineCapability]
    lifecycle_phase: LifecyclePhase

    def initialize(self, context: ExecutionContextProtocol) -> None:
        """Prepare engine state, allocate memory channels, establish internal handles."""
        ...

    def validate(self, context: ExecutionContextProtocol) -> None:
        """Verify parameters, check environment prerequisites, ensure governance approvals."""
        ...

    def execute(self, context: ExecutionContextProtocol) -> EngineResultProtocol:
        """Execute core engine computation deterministically and return EngineResult."""
        ...

    def publish(self, context: ExecutionContextProtocol) -> None:
        """Publish emitted events and generated artifacts to central system buses."""
        ...

    def shutdown(self, context: ExecutionContextProtocol) -> None:
        """Release allocated handles, flush buffers, transition safely to SHUTDOWN."""
        ...


class BaseKernelEngine(ABC):
    """
    Abstract Base Class providing concrete baseline implementations and enforcing
    the strict 5-stage lifecycle contract for Wilsy OS engines.
    """

    def __init__(self, engine_name: str, version: str) -> None:
        self.engine_name: str = engine_name
        self.version: str = version
        self.capabilities: List[EngineCapability] = [EngineCapability.READ_ONLY]
        self.lifecycle_phase: LifecyclePhase = LifecyclePhase.UNINITIALIZED

    @abstractmethod
    def initialize(self, context: ExecutionContextProtocol) -> None:
        self.lifecycle_phase = LifecyclePhase.INITIALIZED

    @abstractmethod
    def validate(self, context: ExecutionContextProtocol) -> None:
        self.lifecycle_phase = LifecyclePhase.VALIDATED

    @abstractmethod
    def execute(self, context: ExecutionContextProtocol) -> EngineResultProtocol:
        self.lifecycle_phase = LifecyclePhase.EXECUTED

    @abstractmethod
    def publish(self, context: ExecutionContextProtocol) -> None:
        self.lifecycle_phase = LifecyclePhase.PUBLISHED

    @abstractmethod
    def shutdown(self, context: ExecutionContextProtocol) -> None:
        self.lifecycle_phase = LifecyclePhase.SHUTDOWN
