"""
===============================================================================
WILSY ENGINEERING KERNEL
===============================================================================
Epitome:
    Artifact Bus Framework - Institutional Index & Query Catalog (FG150C).
    Provides structured query indexing over stored artifacts without managing
    underlying physical persistence media.

Biblical Scale & Architecture:
    High-performance in-memory indexing layer enabling rapid queries by execution,
    engine, type, and temporal history.
    1 Chronicles 9:22 - "All these were chosen... whom David and Samuel the seer established in their office of trust."

Collaboration & Maintenance:
    - [Architecture]: Pure indexing and query facade decoupled from storage media.
    - Consumes: Immutable Artifact instances or catalog registrations.
    - Produces: Filtered artifact collections, histories, and latest references.
    - Maintained by Wilson Khanyezi & Core Engineering.
===============================================================================
"""

from __future__ import annotations

from typing import Dict, List, Optional, Tuple

from tools.eos.artifacts.artifact import Artifact


class ArtifactCatalog:
    """
    Institutional indexing engine providing advanced multi-dimensional queries
    over registered artifacts.
    """

    def __init__(self) -> None:
        # Primary index: artifact_id -> Artifact
        self._artifacts: Dict[str, Artifact] = {}
        # Secondary indexes for lightning-fast queries
        self._by_execution: Dict[str, List[str]] = {}
        self._by_engine: Dict[str, List[str]] = {}
        self._by_type: Dict[str, List[str]] = {}

    def register(self, artifact: Artifact) -> None:
        """
        Registers an artifact into the catalog indices.

        Args:
            artifact (Artifact): Immutable artifact to index.
        """
        art_id = artifact.artifact_id
        self._artifacts[art_id] = artifact

        # Index by execution_id
        if artifact.execution_id not in self._by_execution:
            self._by_execution[artifact.execution_id] = []
        if art_id not in self._by_execution[artifact.execution_id]:
            self._by_execution[artifact.execution_id].append(art_id)

        # Index by engine_id
        if artifact.engine_id not in self._by_engine:
            self._by_engine[artifact.engine_id] = []
        if art_id not in self._by_engine[artifact.engine_id]:
            self._by_engine[artifact.engine_id].append(art_id)

        # Index by artifact_type
        if artifact.artifact_type not in self._by_type:
            self._by_type[artifact.artifact_type] = []
        if art_id not in self._by_type[artifact.artifact_type]:
            self._by_type[artifact.artifact_type].append(art_id)

    def unregister(self, artifact_id: str) -> None:
        """Removes an artifact from all catalog indexes."""
        artifact = self._artifacts.pop(artifact_id, None)
        if not artifact:
            return

        if artifact.execution_id in self._by_execution:
            if artifact_id in self._by_execution[artifact.execution_id]:
                self._by_execution[artifact.execution_id].remove(artifact_id)

        if artifact.engine_id in self._by_engine:
            if artifact_id in self._by_engine[artifact.engine_id]:
                self._by_engine[artifact.engine_id].remove(artifact_id)

        if artifact.artifact_type in self._by_type:
            if artifact_id in self._by_type[artifact.artifact_type]:
                self._by_type[artifact.artifact_type].remove(artifact_id)

    def clear(self) -> None:
        """Clears all catalog indices."""
        self._artifacts.clear()
        self._by_execution.clear()
        self._by_engine.clear()
        self._by_type.clear()

    # [FUNCTION EXPLANATION]: Returns all cataloged artifacts sorted chronologically.
    def all(self) -> Tuple[Artifact, ...]:
        """
        Retrieves all registered artifacts sorted by creation timestamp (oldest to newest).
        """
        sorted_arts = sorted(self._artifacts.values(), key=lambda a: a.created_at)
        return tuple(sorted_arts)

    # [FUNCTION EXPLANATION]: Queries artifacts produced by a specific execution run.
    def by_execution(self, execution_id: str) -> Tuple[Artifact, ...]:
        """
        Retrieves all artifacts produced during a specific execution ID.
        """
        art_ids = self._by_execution.get(execution_id, [])
        arts = [self._artifacts[aid] for aid in art_ids if aid in self._artifacts]
        return tuple(sorted(arts, key=lambda a: a.created_at))

    # [FUNCTION EXPLANATION]: Queries artifacts generated by a specific engine.
    def by_engine(self, engine_id: str) -> Tuple[Artifact, ...]:
        """
        Retrieves all artifacts generated by a specific engine ID.
        """
        art_ids = self._by_engine.get(engine_id, [])
        arts = [self._artifacts[aid] for aid in art_ids if aid in self._artifacts]
        return tuple(sorted(arts, key=lambda a: a.created_at))

    # [FUNCTION EXPLANATION]: Queries artifacts matching a specific domain type classification.
    def by_type(self, artifact_type: str) -> Tuple[Artifact, ...]:
        """
        Retrieves all artifacts matching a given artifact type.
        """
        art_ids = self._by_type.get(artifact_type, [])
        arts = [self._artifacts[aid] for aid in art_ids if aid in self._artifacts]
        return tuple(sorted(arts, key=lambda a: a.created_at))

    # [FUNCTION EXPLANATION]: Returns the most recently created artifact globally or filtered by engine/type.
    def latest(
        self,
        engine_id: Optional[str] = None,
        artifact_type: Optional[str] = None,
        execution_id: Optional[str] = None,
    ) -> Optional[Artifact]:
        """
        Retrieves the single most recent artifact matching optional filters.
        """
        pool = self._artifacts.values()

        if execution_id:
            pool = [self._artifacts[aid] for aid in self._by_execution.get(execution_id, []) if aid in self._artifacts]
        if engine_id:
            pool = [a for a in pool if a.engine_id == engine_id]
        if artifact_type:
            pool = [a for a in pool if a.artifact_type == artifact_type]

        if not pool:
            return None

        return max(pool, key=lambda a: a.created_at)

    # [FUNCTION EXPLANATION]: Returns chronological audit history for a specific engine or artifact type.
    def history(
        self,
        engine_id: Optional[str] = None,
        artifact_type: Optional[str] = None,
    ) -> Tuple[Artifact, ...]:
        """
        Retrieves complete chronological evolution history filtered by engine or type.
        """
        pool = self._artifacts.values()
        if engine_id:
            pool = [a for a in pool if a.engine_id == engine_id]
        if artifact_type:
            pool = [a for a in pool if a.artifact_type == artifact_type]

        return tuple(sorted(pool, key=lambda a: a.created_at))
