"""Unit certification for canonical immutable execution command authority.

VERSION: v1.0.0-KENNEL-FINANCIAL-EXECUTION-COMMAND-UNIT-CERT
TITLE: Financial Execution Command Unit Certification
PURPOSE: Certify authorized command material, boundaries, and fingerprint compatibility.
AUTHORITY: Certification evidence only; no persistence, transport, truth, or settlement authority.
COLLABORATION / OWNERSHIP: Wilson Khanyezi (Founder); Codex (AI Engineering)
ABSOLUTE CANONICAL PATH: /Users/wilsonkhanyezi/legal-doc-system/tests/unit/test_financial_execution_command.py
CERTIFICATION DATE: 2026-08-28
COMPLIANCE: POPIA | GDPR | SOC2
SECURITY / PRIVACY: deterministic opaque references; no credentials or provider payloads.
TENANT BOUNDARY: fixed tenant and obligation identities are immutable in every fixture.
FINANCIAL TRUTH BOUNDARY: command instruction is not provider observation, execution truth, or settlement.
TRANSACTION BOUNDARY: pure unit tests; no Mongo, session, transaction, clock, or I/O.
FIXTURE POSTURE: fixed values and timezone-aware timestamps only.
FINGERPRINT POSTURE: exact synchronous payload keys and SHA3-512 serialization are asserted.
CHANGELOG: v1.0.0 certifies the canonical execution-command domain contract.
"""
from dataclasses import fields
from datetime import datetime, timedelta, timezone
import hashlib
import json

import pytest

from tools.eos.kennel.domain.financial_execution_command import FinancialExecutionCommand, FinancialExecutionCommandError

NOW = datetime(2026, 8, 28, 12, 0, tzinfo=timezone.utc)


def command(**changes: object) -> FinancialExecutionCommand:
    """Build a deterministic complete command fixture."""
    values: dict[str, object] = {
        "tenant_id": "tenant-1",
        "payable_id": "payable-1",
        "release_authorization_id": "release-1",
        "execution_command_id": "command-1",
        "idempotency_key": "idem-1",
        "amount_minor": 12500,
        "currency": "ZAR",
        "payment_destination_reference": "destination-ref-1",
        "created_at": NOW,
        "provider_name": "PAYSHAP",
        "provider_metadata_reference": "provider-metadata-1",
    }
    values.update(changes)
    return FinancialExecutionCommand(**values)  # type: ignore[arg-type]


def test_valid_construction_preserves_all_authorized_material() -> None:
    """Prove every command-owned field is preserved exactly."""
    item = command()
    assert item.tenant_id == "tenant-1"
    assert item.payable_id == "payable-1"
    assert item.release_authorization_id == "release-1"
    assert item.execution_command_id == "command-1"
    assert item.idempotency_key == "idem-1"
    assert item.amount_minor == 12500
    assert item.currency == "ZAR"
    assert item.payment_destination_reference == "destination-ref-1"
    assert item.created_at == NOW
    assert item.provider_name == "PAYSHAP"
    assert item.provider_metadata_reference == "provider-metadata-1"


@pytest.mark.parametrize("field", ["tenant_id", "payable_id", "release_authorization_id", "execution_command_id", "idempotency_key", "payment_destination_reference"])
def test_required_identity_rejects_blank_values(field: str) -> None:
    """Prove required identities fail closed at the domain boundary."""
    with pytest.raises(FinancialExecutionCommandError):
        command(**{field: " "})


@pytest.mark.parametrize("value", [0, -1, True, 1.5, "12500"])
def test_amount_requires_positive_integer(value: object) -> None:
    """Prove command amount is unambiguous positive integer material."""
    with pytest.raises(FinancialExecutionCommandError):
        command(amount_minor=value)


@pytest.mark.parametrize("value", ["", "zar", "ZA", "ZARR", "12A", 123])
def test_currency_requires_uppercase_three_letters(value: object) -> None:
    """Prove currency follows the frozen uppercase three-letter contract."""
    with pytest.raises(FinancialExecutionCommandError):
        command(currency=value)


@pytest.mark.parametrize("value", ["", " ", "bank-account-secret", "card-token"])
def test_destination_reference_is_opaque_and_non_secret(value: str) -> None:
    """Prove blank and credential-like destination material is rejected."""
    with pytest.raises(FinancialExecutionCommandError):
        command(payment_destination_reference=value)


def test_provider_intent_is_optional_but_metadata_remains_opaque() -> None:
    """Prove optional pre-transport provider intent has no result semantics."""
    assert command(provider_name=None, provider_metadata_reference=None).provider_name is None
    with pytest.raises(FinancialExecutionCommandError):
        command(provider_metadata_reference="credential-token")


def test_created_at_requires_explicit_aware_datetime() -> None:
    """Prove command creation time is explicit and never generated by a clock."""
    assert command(created_at=NOW.astimezone(timezone(timedelta(hours=2)))).created_at.tzinfo is not None
    with pytest.raises(FinancialExecutionCommandError):
        command(created_at=datetime(2026, 8, 28, 12, 0))
    with pytest.raises((FinancialExecutionCommandError, TypeError)):
        command(created_at=None)


def test_command_and_idempotency_identities_remain_distinct() -> None:
    """Prove command identity and idempotency identity are separate fields."""
    item = command(execution_command_id="command-a", idempotency_key="idem-b")
    assert item.execution_command_id != item.idempotency_key


def test_fingerprint_matches_synchronous_command_payload() -> None:
    """Prove exact compatibility with frozen synchronous command serialization."""
    item = command()
    expected_payload = {"tenant_id": "tenant-1", "payable_id": "payable-1", "release_authorization_id": "release-1", "execution_command_id": "command-1", "idempotency_key": "idem-1", "amount_minor": 12500, "currency": "ZAR", "payment_destination_reference": "destination-ref-1", "requested_provider": "PAYSHAP", "provider_metadata_reference": "provider-metadata-1"}
    expected = hashlib.sha3_512(json.dumps(expected_payload, sort_keys=True, separators=(",", ":"), ensure_ascii=True).encode("utf-8")).hexdigest()
    assert item.evidence_payload() == expected_payload
    assert item.fingerprint == expected


def test_fingerprint_is_deterministic_and_excludes_created_at() -> None:
    """Prove semantic fingerprint determinism and historical timestamp exclusion."""
    first = command()
    second = command(created_at=NOW + timedelta(days=1))
    assert first.fingerprint == second.fingerprint
    assert len(first.fingerprint) == 128
    assert all(character in "0123456789abcdef" for character in first.fingerprint)


@pytest.mark.parametrize("field", ["tenant_id", "payable_id", "release_authorization_id", "execution_command_id", "idempotency_key", "amount_minor", "currency", "payment_destination_reference", "provider_name", "provider_metadata_reference"])
def test_fingerprint_binds_authoritative_fields(field: str) -> None:
    """Prove each synchronous semantic field changes the command fingerprint."""
    replacements: dict[str, object] = {"amount_minor": 12501, "currency": "USD", "provider_name": "OTHER", "provider_metadata_reference": "metadata-2"}
    replacement = replacements.get(field, f"changed-{field}")
    assert command().fingerprint != command(**{field: replacement}).fingerprint


def test_provider_generated_fields_are_absent_and_object_is_immutable() -> None:
    """Prove command contains no provider outcome or settlement surface."""
    names = {field.name for field in fields(FinancialExecutionCommand)}
    assert {"execution_status", "executed_at", "provider_execution_reference", "provider_evidence_reference", "provider_occurred_at", "settlement_state"}.isdisjoint(names)
    with pytest.raises(AttributeError):
        command().amount_minor = 1  # type: ignore[misc]
    assert not hasattr(command(), "persist")
    assert not hasattr(command(), "settle")
    assert not hasattr(command(), "create")


# ARTIFACT: test_financial_execution_command.py
# VERSION: v1.0.0-KENNEL-FINANCIAL-EXECUTION-COMMAND-UNIT-CERT
# AUTHORITY BOUNDARY: certification evidence only; no execution or settlement authority.
# END OF WILSY OS SOVEREIGN ARTIFACT
